### ISSUE TITLE
[Table Component Feature] 自定义列高级用法，传入的组件的 props 希望添加 column 的 title 属性

### ISSUE THREAD

**Issue by ly525** [Happy-Coding-Clans/vue-easytable#105]
> [Table Component Feature] component need column title as prop when custom column

[文档](http://doc.huangsw.com/vue-easytable/app.html#/table?anchor=table-custom-columns)中提及可以使用 组件来自定义列，实际应用中发现一处场景，table 的某一列 column 内容过长，会使用 `...`省略，为了增强用户体验，并没有使用 title 属性做提示（默认 delay 时间 2s 过长），所以会 用一个 tooltip 来提示用户，提示的内容分为两部分：当前单元格的 title（title 和 field 不同） 和 当前单元格的 内容。
但是 组件接受的 props 只有 `rowDate, field, index`， 因此麻烦您在 props 里面可以提供下 title 这个字段吗？

效果如图所示：

![image](https://user-images.githubusercontent.com/12668546/35607958-e1c2fd68-0691-11e8-8412-766f9dd326f9.png)

**Comment by huangshuwei** [comment]
可以的，不过如果是复杂表头的场景会有些问题，如果是合并的表头，那么列对应的title 不好确定。
我可以把 `columns` 以及 `titleRows` 都传到自定义组件中。根据业务需求拼装数据
