### ISSUE TITLE
拖动改变列宽后（缩小），不能重新计算最后一列宽度

### ISSUE THREAD

**Issue by zongpengz** [Happy-Coding-Clans/vue-easytable#107]
![qq 20180205152245](https://user-images.githubusercontent.com/22546341/35792545-b59a3d46-0a88-11e8-8140-0611478846da.png)
如图能不能在缩小某列宽之后，最后一列撑满右侧，不要出现留白

**Comment by jxharp** [comment]
我们也遇到了，设计上表格宽度是固定的，拖动列宽不应该改变表格整体宽度，不然页面留白很难看。

**Comment by jxharp** [comment]
参见饿了么的表格，拖动不改变整个表格宽度是合理的
http://element-cn.eleme.io/#/zh-CN/component/table

**Comment by huangshuwei** [comment]
@jxharp 
饿了么这种方式感觉也不合理啊，我之前的版本也是按照这种方式做的。按照这种方式，列宽的拖动会影响到最后一列，其他列的宽度增加，最后一列将越来越小

**Comment by jxharp** [comment]
这个没有绝对的对错，但是我的几个用户看了后，都觉得不合理。UI设计师看过了，她任务当一个页面有2列都是表格，或者布局确定的情况下， 拖动导致整体后面露出一片空白，其实是破坏了设计师的设计。用户也会觉得别扭。
