### ISSUE TITLE
行内编辑功能

### ISSUE THREAD

**Issue by CodeMonkeyXu** [Happy-Coding-Clans/vue-easytable#11]
不单独单元格编辑 双击一行实现行内所有可编辑单元格处于编辑状态,
且单元格内容不一样,有文本框/数字框/日期选择框/下拉框等

**Comment by zwgshr** [comment]
大概是这个样子
![image](https://user-images.githubusercontent.com/10608334/31433141-fbc49364-aeaa-11e7-84f3-98f6d3c4eb3b.png)

**Comment by huangshuwei** [comment]
@zwgshr 
收到

**Comment by sunriseyuen** [comment]
行内编辑不好用，如果可以实现这个就好

https://handsontable.com/examples.html?headers

**Comment by huangshuwei** [comment]
@sunriseyuen 
收藏，后面优化时参考
