### ISSUE TITLE
table 中的值可以是icon(html碼)

### ISSUE THREAD

**Issue by mixwade32517** [Happy-Coding-Clans/vue-easytable#111]
想知道json的value中能否塞html碼?
像是<i class="fa fa-plus"></i>
<img width="887" alt="2018-02-14 11 40 21" src="https://user-images.githubusercontent.com/8232987/36192847-60d4659e-119e-11e8-9183-7420d095629c.png">

**Comment by ly525** [comment]
table body 内 icon 可以实现，使用 `componentName`  给该列传入自定义组件。[Docs-customColumns](http://doc.huangsw.com/vue-easytable/app.html#/table/customColumns)

table header 自定义组件暂时还不支持。

PS：麻烦先仔细阅读文档，谢谢
