### ISSUE TITLE
How to hide/show entire columns(fields and title) programmatically using a form filter which selects which fields to show in table?

### ISSUE THREAD

**Issue by ian-pinto-vamaship** [Happy-Coding-Clans/vue-easytable#120]
How to hide/show entire columns(fields and title) programmatically using a form filter which selects which fields to show in table?

**Comment by huangshuwei** [comment]
Now all the fields set in the `columns ` object will be displayed,
 if you want to hide some fields can only be excluded from the `columns` object.

But you can define a function in the `methods` to filter the fields to be displayed,like 
```
...
data(){
   return {
      columns:[...],
      currentColumns:[...]  // table comp columns option
  }
},
methods{
    filterFields(){
         
          this.currentColumns = columns.filter(...)
   }
}
...
```
