### ISSUE TITLE
纵向自适应问题

### ISSUE THREAD

**Issue by wxf1994** [Happy-Coding-Clans/vue-easytable#133]
![image](https://user-images.githubusercontent.com/24525956/37812471-2918bece-2e9b-11e8-833e-45bacdeed5f3.png)
如上图所示，当数据不是很多时，表格下面会有空白，如何把空白去除，如果根据行高强制给表格设置高度时，又会出现纵向的滚动条，但是业务需求是不需要滚动条，该怎么设置呢？

**Comment by huangshuwei** [comment]
设置纵向自适应，参考：
http://doc.huangsw.com/vue-easytable/app.html#/table/verticalResize

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
