### ISSUE TITLE
侧边主菜单缩放，右边的table不能自适应

### ISSUE THREAD

**Issue by iTestinglab** [Happy-Coding-Clans/vue-easytable#143]
你好这个问题修复了没，我看之前就有人提过这个bug，现在的版本还有这个问题，请问下什么时候修复啊，急！！

**Comment by huangshuwei** [comment]
我最近有时间了，修复了通知你

**Comment by huangshuwei** [comment]
#104

**Comment by iTestinglab** [comment]
@huangshuwei ，修复了第一时间告诉我哦，thanks

**Comment by iTestinglab** [comment]
hello，@huangshuwei  这个问题修复没

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
