### ISSUE TITLE
纵向整列拖动如果实现了，是不是跟列宽度拖动起冲突

### ISSUE THREAD

**Issue by BlackEyeByLee** [Happy-Coding-Clans/vue-easytable#144]
自己用的是ELEMENT的表格和sortable拖拽去做整列拖动，然后跟列宽度拖动起了一点点的冲突

**Comment by huangshuwei** [comment]
是的，不过可以指定拖动的范围。即在一定范围内是整列拖动，其他范围内是列宽拖动。
我目前还没去实现

**Comment by minzhenyu** [comment]
@huangshuwei 这个有实现计划吗？
