### ISSUE TITLE
多选模式表格行选中的背景颜色

### ISSUE THREAD

**Issue by guowangsheng** [Happy-Coding-Clans/vue-easytable#147]
能否多选模式勾选的表格行选中的背景颜色都和单击的一致呢

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
