### ISSUE TITLE
分页组件国际化

### ISSUE THREAD

**Issue by coblan** [Happy-Coding-Clans/vue-easytable#148]
分页组件里面要显示几个文字，例如共多少页，前往多少页
请问怎么样能够翻译成英文，还有繁体。

**Comment by ly525** [comment]
现在这些文案信息是直接作为 hard code 写在代码里面，目前没有提供 接口，让用户来自定义。国际化已经放在计划上了，麻烦稍等一段时间，国际化方案上线之后，会即使通知的。

**Comment by coblan** [comment]
好的，谢谢，辛苦了。
现在我暂时修改源代码实现了。

**Comment by fanxiaolong** [comment]
还有就是 columns  里面的 title 字段  也需要国际化哦.当我用 vue-i18n 切换的时候,title里的值,不会变动.

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
