### ISSUE TITLE
请问, 能增加一个自定义表头中的某个单元格内容吗

### ISSUE THREAD

**Issue by Zzeo** [Happy-Coding-Clans/vue-easytable#155]
如题

**Comment by ly525** [comment]
非常感谢你的建议，好问题。已经列入开发计划，如果上线了，我们会及时更新该 issue 状态的

**Comment by huangshuwei** [comment]
The new version has solved this problem. [header cell custom content](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/cell-custom?anchor=header-zi-ding-yi-dan-yuan-ge)
 
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
