### ISSUE TITLE
[提問] 表格資料排序

### ISSUE THREAD

**Issue by likol** [Happy-Coding-Clans/vue-easytable#156]
sort-change 接收一個 params 參數
假設現在有一個以上的欄位可以進行排序
但 params 得到的是所有 field 的排序資料
無法得知用戶實際上點擊排序的欄位

請問如何解決？

**Comment by ly525** [comment]
1. 你的排序方式是 `多字段排序` 还都是 `单字段排序`，具体参见[文档](http://doc.huangsw.com/vue-easytable/app.html#/table/sort)
2. 如果是 `单字段排序`，这个问题的答案就在params 里面
```
sortChange(params) {
      let field = ''
      // 得到点击的列 和 排序方式。
      for (var col in params) { if (params[col]) field = col }
      let order = params[field]
      
    },
```

3. 如果是多字段排序，你是知道你预先设置的排序列以及其排序方式的
比如这样
```
columns: [
   {field: 'name', title: '姓名', orderBy:'asc',isResize:true},
   {field: 'tel', title: '手机号码', orderBy:'desc',isResize:true},
]
```
可以得到初始的排序方式为：
```
{"name":"asc","tel":"desc"}
```

以 点击 姓名， 逆序排列为例，得到的 `params` 如下
```
{"name":"desc","tel":"desc"}
```

这两个 Object 可以做一下 diff，就可以得到对应的点击列了。

当然以上仅仅是临时解决方案，这边暴露的API 确实是有需要改进和优化的地方，已经记下，更新之后，我们即使通知的，非常感谢。
