### ISSUE TITLE
最后的单元格合并，样式有问题

### ISSUE THREAD

**Issue by shiyuan17** [Happy-Coding-Clans/vue-easytable#157]
![image](https://user-images.githubusercontent.com/4144030/39081819-ac90dbd8-457a-11e8-99e2-f8ab68fef332.png)

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)

**Comment by abc123lzq** [comment]
一样问题怎么解决？

**Comment by 0131LWG** [comment]
一样的问题，有解决的方案吗？

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
