### ISSUE TITLE
当同时有 排序, 自定义列宽, 排序功能时, 会出现事件冒泡

### ISSUE THREAD

**Issue by Zzeo** [Happy-Coding-Clans/vue-easytable#160]
![image](https://user-images.githubusercontent.com/26971142/39222246-47a045dc-486e-11e8-8425-829df606fd02.png)

**Comment by ly525** [comment]
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle。
Please provide a reproduction link, like codepen or jsfiddle

**Comment by huangwenlong528** [comment]
官方上面的排序是需要自己写的，但是我不知道在  sortChange(params){ }里面该怎么写。上面说是重新请求数据，但只是重新请求数据就可以了吗？具体该怎么写呢？还请大神讲解一下。

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
