### ISSUE TITLE
默认排序列设置

### ISSUE THREAD

**Issue by ly525** [Happy-Coding-Clans/vue-easytable#161]
请教一个问题，在文档中的这个[例子](http://doc.huangsw.com/vue-easytable/app.html#/table/sort)里面，对两个列设置了 orderBy.
但是，官网的例子 和 jsfiddle 中，只有第一个设置了orderBy 的列的icon产生了高亮效果.
可以配置某个列作为默认排序列， 然后开启该列对应的排序 icon高亮吗？
![3641524708499_ pic_hd](https://user-images.githubusercontent.com/12668546/39299658-d60d4366-497b-11e8-9641-2df6dcf0e782.jpg)

![3601524708442_ pic_hd](https://user-images.githubusercontent.com/12668546/39299600-b3933dfe-497b-11e8-899b-35a49d101897.jpg)

**Comment by skillnull** [comment]
这个问题解决了吗？动态数据每次调接口，都会变成第一列高亮

**Comment by huangwenlong528** [comment]
官方上面的排序是需要自己写的，但是我不知道在  sortChange(params){ }里面该怎么写。上面说是重新请求数据，但只是重新请求数据就可以了吗？具体该怎么写呢？还请大神讲解一下。
