### ISSUE TITLE
列表头内容是英文的时候，换行时出现单词被截断的情况

### ISSUE THREAD

**Issue by ricpi** [Happy-Coding-Clans/vue-easytable#165]

**Comment by ly525** [comment]
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle。
Please provide a reproduction link, like codepen or jsfiddle

**Comment by ly525** [comment]
了解，这个问题可以通过 覆盖 table header 里面的 单元格 的样式来实现。已经暴露了 API，具体请参照文档
[文档-单元格样式](http://doc.huangsw.com/vue-easytable/app.html#/table/cellStyle)

**Comment by ricpi** [comment]
这是在线示例，https://jsfiddle.net/837rhax2/2/
![11_05_59__05_08_2018](https://user-images.githubusercontent.com/5546157/39735915-436919c0-52b0-11e8-83eb-8c7742a33e1c.jpg)
如截图里'months'就是被截断了，可以麻烦看下设置的覆盖样式是否正确？

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
