### ISSUE TITLE
单元格编辑控制的新逻辑

### ISSUE THREAD

**Issue by nxjdec82** [Happy-Coding-Clans/vue-easytable#172]
目前能实现设置表格的某一列可以控制编辑或非编辑状态
有一个新的需求：
能不能根据某一行的数据条件实现改行是否可以编辑

应用场景：
假设列C设置的是可以编辑，行5，由于某个因素，该行不能编辑
那么C5单元格则不能编辑；
假设列C设置的是不能编辑的；行5，由于某个因素，改行设置的可以编辑
那么C5单元格则不能编辑；
假设列C设置的是可以编辑；行5，设置的可以编辑
那么C5单元格则可以编辑

需求或问题：
也能实现数据行可以根据条件设置改行是否可编辑
当列能编辑，行也能根据条件可以编辑，则交叉的单元格可以编辑

**Comment by zibuyu1** [comment]
> 理解，我们现在的编辑的颗粒度是到 column 级别，
> 你需要的是颗粒度是到 单元格的，
> 这确实是一个蛮好的需求，非常感谢反馈

**Comment by zibuyu1** [comment]
动态生成的表格，点击每一个单元格时需要发送接口判断这个单元格是否可以编辑，这个怎么实现呢
