### ISSUE TITLE
点击列排序问题

### ISSUE THREAD

**Issue by daminga** [Happy-Coding-Clans/vue-easytable#178]
点击排序的时候能获取的是当前点击的列吗？判断按当前点击的排序！没有相关例子！获取的也不是当前点击的列的信息

**Comment by daminga** [comment]
这个问题源码我优化了。提交?

**Comment by ly525** [comment]
欢迎 pull request

**Comment by ShengChangWei** [comment]
你好，我也遇到同样的需求，点击排序获取当前点击的列，请问这个解决了吗，谢谢

**Comment by huangwenlong528** [comment]
官方上面的排序是需要自己写的，但是我不知道在  sortChange(params){ }里面该怎么写。上面说是重新请求数据，但只是重新请求数据就可以了吗？具体该怎么写呢？还请大神讲解一下。

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
