### ISSUE TITLE
有没有点击某行，在当前的这行td下面显示一个自定义内容

### ISSUE THREAD

**Issue by 3429490638** [Happy-Coding-Clans/vue-easytable#183]
类似于展开当前行，这样不用所有的数据都显示成一行。

**Comment by 3429490638** [comment]
element 表格的 展开行

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
