### ISSUE TITLE
当数据量很大时 ，使用 column-width-drag 会导致卡顿

### ISSUE THREAD

**Issue by my9074** [Happy-Coding-Clans/vue-easytable#184]
当数据量很大时 (10000行，N 列，无分页)，添加 column-width-drag 属性后，拖拽会导致页面重绘，造成卡顿。

**Comment by my9074** [comment]
DEMO: [jsfiddle](https://jsfiddle.net/2fz7tuq8/1/)
还请教个问题，是怎么做到大数据量时，保证浏览器不卡顿的呢？

**Comment by xianziljl** [comment]
可以试试 
vue-virtual-scroller, 不知道两者能不能结合到一块儿。

**Comment by my9074** [comment]
vue-virtual-scroller 对原生 table 支持比较好，但是像这种封装过的 table components 可能不太适配
