### ISSUE TITLE
排序的时候 params 多接受到一个“”

### ISSUE THREAD

**Issue by passballking** [Happy-Coding-Clans/vue-easytable#185]
我在做排序的时候点击排序按钮发现 params 会产生三个值： "asc", "desc" 和空值 “”，我想实现点击排序按钮就只会在 asc 和 desc 之间切换，我现在的做法是当 params === ""的时候强制让它等于 'asc'。请问这个空值是有什么特别安排么？

**Comment by skillnull** [comment]
http://doc.huangsw.com/vue-easytable/app.html#/table/api
sort-always设置只在升序和倒序切换就不会出现空值了

**Comment by huangwenlong528** [comment]
排序的话演示里面写的需要重新请求数据，还需要做一些其他的操作吗？难道直接请求数据吗？我不知道该怎么写。还请大神讲解一下

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
