### ISSUE TITLE
单字段排序icon高亮问题

### ISSUE THREAD

**Issue by skillnull** [Happy-Coding-Clans/vue-easytable#186]
默认第一列高亮，点击其他列还是第一列高亮，将sort-control-mixin.js文件中的 this.singleSortInit(); 这一行调用方法注释掉可以实现正常高亮。会不会影响其他功能还未知，目前没有发现，不知道有没有其他解决方法，望处理一下这个问题。 @huangshuwei

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
