### ISSUE TITLE
固定表头和列，导致排序功能无法使用

### ISSUE THREAD

**Issue by evarainy** [Happy-Coding-Clans/vue-easytable#188]
你好。固定表头和固定列后，导致排序功能无法使用。我查看的是官方案列（http://doc.huangsw.com/vue-easytable/app.html#/table/fixedColumnsTitle）。请问是兼容问题还是BUG？

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)

**Comment by huangwenlong528** [comment]
排序的话演示里面写的需要重新请求数据，还需要做一些其他的操作吗？难道直接请求数据吗？我不知带该怎么写。还请大神讲解一下

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
