### ISSUE TITLE
小功能建议 - 希望可以支持《拖动选中一些连续的row》的模式

### ISSUE THREAD

**Issue by lilong7676** [Happy-Coding-Clans/vue-easytable#189]
![image](https://user-images.githubusercontent.com/21004230/40968186-8fbafada-68e7-11e8-845e-95bff14e9e13.png)
如图，鼠标点击左侧序列单元格选中整行，拖动可多选行。

**Comment by ly525** [comment]
有点像 Excel 的 长按、滑动、选中，我们会做一些调研的，如果觉得合适，会列入开发计划。
非常感谢，不错的建议
