### ISSUE TITLE
请问栏位能否自动换行呢

### ISSUE THREAD

**Issue by jhihsiying** [Happy-Coding-Clans/vue-easytable#190]
如果栏位里的文字超出栏位宽度，会自动变成「...」来省略超出的部份，请问有办法让他自动换行吗？

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)

**Comment by shenahobo** [comment]
我看高度只是默认40,可以动态的计算高度,让每一行自动换行吗?下面是jsfiddle

**Comment by jhihsiying** [comment]
您好，先暂时提供图片
就拿官方的 RWD 例子来说

![Image of vue easy table](https://s3.amazonaws.com/jhihsiyingweb/Other/vue+easy+table.jpg)
栏位里的文字超出栏位宽度，会自动变成「...」来省略超出的部份
希望可以自动换行

**Comment by ly525** [comment]
源码中作者应该加了如下处理：
```CSS
white-space: nowrap;
text-overflow: ellipsis;
overflow: hidden;
```

你可以通过自定义组件或者覆盖作者的css 来实现自动换行的需求。
如有问题，欢迎继续补充

**Comment by Apple-Flavor** [comment]
这个feature做好了么？ 感觉这个很重要啊。 能不能麻烦告诉个方法？

**Comment by Apple-Flavor** [comment]
@jhihsiying 请问你有按照 @ly525 的方法试过么？能不能share一下怎么做到自动换行的？感谢

**Comment by jhihsiying** [comment]
@Apple-Flavor 我最后没有试出来，所以放弃使用这个 table 了。
如果取消掉 overflow 和 text-overflow，只会让原本的 "..." 不见而已，字并不会出来。
不知道是我哪里没有用好还是怎么回事。
于是我放弃使用这个 table 了。

**Comment by MinimalistYing** [comment]
同需求

**Comment by Davisjy** [comment]
@jhihsiying 请问换了哪个table能告知吗，同需求自动换行

**Comment by jhihsiying** [comment]
@Davisjy 您好，我最近是使用 vue-tables-2 实作。
给您参考，谢谢。

**Comment by Davisjy** [comment]
@jhihsiying 感谢，不过我修改了样式也实现了

**Comment by jhihsiying** [comment]
@Davisjy 不会，请问可以告诉我是怎么实现的吗？想学习一下。

**Comment by Davisjy** [comment]
@jhihsiying 简书尾部https://www.jianshu.com/p/399332c59c09，谢谢

**Comment by JustSong** [comment]
@Davisjy  Thanks a lot !!!

**Comment by chen2319** [comment]
> https://www.jianshu.com/p/399332c59c09

打不开了。。。

**Comment by chen2319** [comment]
@Davisjy 链接打不开了，是否可以在这里copy出来？

**Comment by chen2319** [comment]
@JustSong 你还有吗？怎么解决的。能否告知。

**Comment by Davisjy** [comment]
@chen2319 链接可以打开，检查网络看看呢

**Comment by chen2319** [comment]
> @chen2319 链接可以打开，检查网络看看呢
谢谢回复，的确网络问题，已解决。
