### ISSUE TITLE
vue.esm.js?65d7:591 [Vue warn]: Error in created hook: "TypeError: __webpack_require__.i(...) is not a function"

### ISSUE THREAD

**Issue by imgwho** [Happy-Coding-Clans/vue-easytable#191]
我直接通过lib文件引用的话  出现这个错误大概是什么原因
[![TIM截图20180607204239.png](https://i.loli.net/2018/06/07/5b192898642e5.png)](https://i.loli.net/2018/06/07/5b192898642e5.png)
[![TIM截图20180607204358.png](https://i.loli.net/2018/06/07/5b1928989bf41.png)](https://i.loli.net/2018/06/07/5b1928989bf41.png)

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)

**Comment by imgwho** [comment]
就是我不通过npm引用，而是按照源码目录里的package里的文件引用  跑不起来  [https://gitee.com/imgwho/vue-easytable](项目地址l)
[![TIM截图20180611123616.png](https://i.loli.net/2018/06/11/5b1dfe37554bc.png)](https://i.loli.net/2018/06/11/5b1dfe37554bc.png)

**Comment by ly525** [comment]
@imgwho  我大概看了下，修改如下代码

https://github.com/huangshuwei/vue-easytable/blob/c835c5a05e111e074e1000f082c3e182965bdc51/packages/src/utils/deepClone.js#L256-L258

替换为 
```JavaScript
// if (typeof module === 'object' && module.exports) {
//     module.exports = clone;
// }
export default clone
```

结果如下：

> ![image](https://user-images.githubusercontent.com/12668546/41340961-23851928-6f2b-11e8-9160-41b277c488b0.png)

问题定位：
 > 和模块机制、babel 编译有关系，我也需要继续学习。应该需要和 @huangshuwei 沟通，将项目的构建打包进行梳理和优化。

@imgwho  如有问题或者好的想法，可以一起讨论

**Comment by imgwho** [comment]
@ly525 非常感谢 问题的确是node 的commonjs规范跟es6模块规范不兼容  然后我看了下项目的 [index.js](https://github.com/huangshuwei/vue-easytable/blob/4a8e00a168152b0aa8d8eb0e6d3ec6709fcd4ef0/packages/index.js#L25) 配置文件发现 `module.exports = {
    VPagination,
    VTable,
    VCheckbox,
    VCheckboxGroup,
    VSelect,
    VDropdown
};`
这里依然是module.exports 然后按照官网文档的引入方式`// 引入样式
import 'vue-easytable/libs/themes-base/index.css'
// 导入 table 和 分页组件
import {VTable,VPagination} from 'vue-easytable'

// 注册到全局
Vue.component(VTable.name, VTable)
Vue.component(VPagination.name, VPagination)`
VPagination组件引用不到  具体原因还望作者有空看一下
