### ISSUE TITLE
能否在列编辑的时候，同时返回当前dom对象呢

### ISSUE THREAD

**Issue by pengdyzhou** [Happy-Coding-Clans/vue-easytable#201]
希望列编辑回调，能返回当前dom对象

**Comment by ly525** [comment]
能否描述下具体的使用场景？以便我们衡量需求

**Comment by pengdyzhou** [comment]
编辑完成要根据数据，进行一些提醒，提醒需要定位到编辑的单元格处，故需要操作

**Comment by ly525** [comment]
https://github.com/huangshuwei/vue-easytable/blob/a2ba10a11dc9892ce4fa49ad2db3150672cda643/packages/v-table/src/cell-edit-mixin.js#L100

我看了下源码，应该是在这里做些修改就OK了，你可以先clone，本地构建下。
我和 @huangshuwei  讨论一下，如果可以，会尽快支持的

**Comment by pengdyzhou** [comment]
好的 我是一个后端人员，前端东西还需要摸索下看看

**Comment by danyzj** [comment]
event.target.parentNode.classList.add("cell-unsave");

event.target 是Input，event.target.parentNode是外围的div
