### ISSUE TITLE
请问很多行的时候，向下滑动，如何实现表头悬浮在顶端多谢

### ISSUE THREAD

**Issue by m1koo** [Happy-Coding-Clans/vue-easytable#205]
![image](https://user-images.githubusercontent.com/15926813/42802014-1b5dc628-89d4-11e8-98c2-b3a61bf0ee36.png)
现在能够悬浮到第四行，但是再往下就消失了

**Comment by m1koo** [comment]
我蠢了，一开始以为纵向自适应是表格的高度是自动计算的（有多少文字全部显示），建议作者修改一下文档为固定表头，这样比较好理解

**Comment by ly525** [comment]
非常感谢，可以说明下是文档的哪一页吗？（贴一下URL或者截图也可以），我们来做一下更新
