### ISSUE TITLE
demo 排序页面失效

### ISSUE THREAD

**Issue by zhoupeihuang** [Happy-Coding-Clans/vue-easytable#213]
http://doc.huangsw.com/vue-easytable/app.html#/table/sort

**Comment by huangwenlong528** [comment]
demo里面写的需要重新请求数据，还需要做一些其他的操作吗？难道直接请求数据吗？还请大神讲解一下。

**Comment by zhoupeihuang** [comment]
太久远了 我都不记得了

**Comment by rockycastaneda** [comment]
http://doc.huangsw.com/vue-easytable/app.html#/table/sort does not sort.  Sort function is broken.
