### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by luoruiqing** [Happy-Coding-Clans/vue-easytable#216]
对一个大概500行40列的数据进行增加类样式的时候会卡顿(大概1分钟), 在不考虑分页的情况下, 作者能否对性能优化一下, 这里的场景是500 ~ 2000 条 40列左右的数据增加列样式
cell-class-name : 是否可以使用settimeout(func,0 ~ 100) 或者其他方式并发起来, 不然处理实在太慢了
cell-merge : 这个方法也是很慢, 有没有啥好办法提升速度

**Comment by luoruiqing** [comment]
暂时使用分页解决了~

**Comment by luoruiqing** [comment]
cellMerge 会在dom里面执行了4次, 这样的话 10 * 10的矩阵会调用400次该方法, 还是希望作者做一些性能上的优化~

**Comment by ly525** [comment]
好建议，已经收到

**Comment by ly525** [comment]
@luoruiqing cellMerge 确实会执行很多遍，原因为是在 template 里面对 cellMerge 做了多次调用，后期对该用 jsx 来重写，会解决这个问题

**Comment by ly525** [comment]
#264

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
