### ISSUE TITLE
checkbox多选取消

### ISSUE THREAD

**Issue by wangfengko** [Happy-Coding-Clans/vue-easytable#218]
checkbox中取消选中不能触发clearCurrentRow方法

**Comment by huangshuwei** [comment]
The new version has solved this problem.  [row checkbox doc](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/row-checkbox)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
