### ISSUE TITLE
表头条件筛选可以动态定义吗?

### ISSUE THREAD

**Issue by benxiaohai1212** [Happy-Coding-Clans/vue-easytable#231]
能否动态加载筛选条件?
如:
```
columns: [
                    {field: 'name', title: '姓名', width: 80, titleAlign: 'center',columnAlign:'center',isResize:true,
                        filterMultiple: true,
                        filters: **filterArray**,
                        isFrozen:true
                    },
```

**Comment by benxiaohai1212** [comment]
可以。下面是我用的方法。仅供参考。
`
data () {
columns: [
                    {field: 'name', title: '姓名', width: 80, titleAlign: 'center',columnAlign:'center',isResize:true,
                        filterMultiple: true,
                        filters: **filterArray**,
                        isFrozen:true
               }]
}, 
created: function () {
        this.getUsers();
 },
 methods: {
        getUsers:function () {
            var users = [];
            $.ajax({
                url: 'xxx',
                type: 'post',
                async: false,
                success: function (result) {
                    var list = result.data;
                    for (i in list) {
                        var user = {};
                        user['label'] = list[i].name;
                        user['value'] = list[i].name;
                        users.push(user);
                    }
                }
            });
//如果列固定可以在此处对filters赋值，如果不固定可以判断field然后赋值。
            this.columns[0].filters = users;
        },
`

**Comment by huangshuwei** [comment]
The new version has solved this problem. demo:http://doc.huangsw.com/vue-easytable/#/zh/doc/table/header-filter-custom

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
