### ISSUE TITLE
能增加行展开吗?

### ISSUE THREAD

**Issue by gloooe** [Happy-Coding-Clans/vue-easytable#232]
展开行
mu-data-table 支持行展开功能，用于展示更多的信息。

**Comment by nicewahson** [comment]
要是有个能手动控制单元格编辑的api就好了

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
