### ISSUE TITLE
关于空表的建议

### ISSUE THREAD

**Issue by navysummer** [Happy-Coding-Clans/vue-easytable#233]
在做项目时候发现，i18n翻译的时候，无法翻译空表中的暂无数据四个字，建议增加这四个字的开启关闭功能

**Comment by ly525** [comment]
@na
好的，收到。国际化的方案也会尽快上线

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
