### ISSUE TITLE
table 的resize事件如何使用？ 

### ISSUE THREAD

**Issue by Lee66** [Happy-Coding-Clans/vue-easytable#234]
切换多个table 时出现table已经渲染了，也可以看到dom元素，但是页面上就是没有，当窗口大小改变时可以出来，在api 中就看到一个resize事件，但是不知道怎么用

**Comment by ly525** [comment]
临时方案：通过 refs 获得 table 实例，类似 this.$refs.table.resize()

具体原因还在排查

**Comment by raymondZhong** [comment]
this.$refs.table.resize()   不行

this.$refs 是空的对象

**Comment by dearestKai** [comment]
这个问题解决了吗？想知道

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
