### ISSUE TITLE
column header click

### ISSUE THREAD

**Issue by luisdesouza** [Happy-Coding-Clans/vue-easytable#235]
How can I execute a method when I click in a column header and get column parameters and execute a function

**Comment by gokigoks** [comment]
I also need this.. is there a way we can send an element as string and have vuetable render it? It would be nice for vue-easytable to expose an api for column functions..

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
