### ISSUE TITLE
关于固定不同的列，固定的列都是在左边的问题的改进建议

### ISSUE THREAD

**Issue by bymomo** [Happy-Coding-Clans/vue-easytable#238]
固定不同的列，固定的列都变成统一出现在左边了，而不是在原来的位置。建议参考iview 的表格中的固定列功能。
iview表格的固定列，那一列原来在什么位置，固定之后就还是在什么位置的，不是直接全部往左边固定了。
或者能设置哪些列固定左边，哪些列固定右边也不错。

![qq 1](https://user-images.githubusercontent.com/28828166/45473404-925fc880-b769-11e8-8cfd-af3fd34a406f.png)
![qq 20180913152212](https://user-images.githubusercontent.com/28828166/45473414-955ab900-b769-11e8-873f-c68136c79a25.png)

**Comment by bymomo** [comment]
代码如下：
![image 1](https://user-images.githubusercontent.com/28828166/45473464-bb805900-b769-11e8-8d60-1315e14d9cf0.png)

**Comment by bymomo** [comment]
或者能设置哪些列固定左边，哪些列固定右边也行。

**Comment by hugheschoi** [comment]
同问

**Comment by garfield02** [comment]
这个问题有没有解决呢？

**Comment by hugheschoi** [comment]
没有，只能做到左边




------------------ 原始邮件 ------------------
发件人: "garfield02"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 中午11:54
收件人: "huangshuwei/vue-easytable"<vue-easytable@noreply.github.com>;
抄送: "Hughes"<845299100@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [huangshuwei/vue-easytable] 关于固定不同的列，固定的列都是在左边的问题的改进建议 (#238)




这个问题有没有解决呢？

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
