### ISSUE TITLE
分页+筛选，翻页或跳转页后筛选失效

### ISSUE THREAD

**Issue by benxiaohai1212** [Happy-Coding-Clans/vue-easytable#243]
如题：
分页筛选，本页筛选没有问题，翻页或跳转到某一页，虽然筛选条件还在，但是已经筛选数据了。

**Comment by ly525** [comment]
closed because we can't reproduce it
因为无法复现 Bug，Issue 将被关闭

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
