### ISSUE TITLE
显示隐藏列的ui

### ISSUE THREAD

**Issue by Zzeo** [Happy-Coding-Clans/vue-easytable#25]
现在已经提供的api是能够实现显示隐藏列,但是并没有一套现成的ui,希望能封装成一个拿来直接用的api

**Comment by huangshuwei** [comment]
需要UI ? 能否再详细说下

**Comment by Zzeo** [comment]
![tim 20171024133654](https://user-images.githubusercontent.com/26971142/31926493-55b0774c-b8c1-11e7-926f-9a8182621152.png)
![tim 20171024133700](https://user-images.githubusercontent.com/26971142/31926494-55e49888-b8c1-11e7-9733-9492a54cb7a1.png)
![tim 20171024133703](https://user-images.githubusercontent.com/26971142/31926495-5615d0d8-b8c1-11e7-85b1-a1da41d9c43b.png)
类似于这样的一个功能

**Comment by huangshuwei** [comment]
好提议，后面加一个👊

**Comment by zhanglin00129** [comment]
+1 for this
