### ISSUE TITLE
is-horizontal-resize:true时列的宽度能否随内容自动撑开？

### ISSUE THREAD

**Issue by NinjaJin** [Happy-Coding-Clans/vue-easytable#250]
表格横向自适应，由于某列内容字数不固定，写固定width不合适，怎么实现列的宽度随内容撑开

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
