### ISSUE TITLE
表格数据重新渲染后未刷新表格的当前高亮行

### ISSUE THREAD

**Issue by woxingxin** [Happy-Coding-Clans/vue-easytable#251]
表格高亮行未能够清除，或者是在分页后没有清楚，此时高亮行已经无法反映选中记录

**Comment by ly525** [comment]
欢迎反馈
麻烦提供能够复现的例子，比如 codepen 或者 jsfiddle，让我们能够复现你的问题。
Please provide a reproduction link, like codepen or jsfiddle

请参照 [Issue 规范](https://github.com/huangshuwei/vue-easytable/wiki/Issue-%E8%A7%84%E8%8C%83)
