### ISSUE TITLE
是否可以对外暴露 全选 或 取消全选 的方法

### ISSUE THREAD

**Issue by chenyo2691** [Happy-Coding-Clans/vue-easytable#253]
希望您可以明白我的意思，让我可以使用this.$refs['table'].selectAll()，类似这样的方法去使得表格全选。取消全选也同理。

**Comment by huangshuwei** [comment]
The new version has solved this problem. [row checkbox doc](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/row-checkbox)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
