### ISSUE TITLE
添加 当内容过长被隐藏时显示  tooltip

### ISSUE THREAD

**Issue by zongpengz** [Happy-Coding-Clans/vue-easytable#26]
**类似于**

![0 i 1jyx5q 2vrig 6ny7](https://user-images.githubusercontent.com/22546341/31926675-a4e9c7c2-b8c2-11e7-81c8-526fb3a8de1b.png)

**Comment by huangshuwei** [comment]
现在是可以通过给`column` 对象的`overflowTitle`，设置是否显示‘title’(原生的)，API中忘了加了😓。不过目前没有自动计算超出自动加tip，这个我优化下

**Comment by zongpengz** [comment]
感谢回复，辛苦了

**Comment by huangshuwei** [comment]
😊
