### ISSUE TITLE
Column filter with input

### ISSUE THREAD

**Issue by stefnats** [Happy-Coding-Clans/vue-easytable#262]
Hi,

i try to filter prices - would it be possible to implement a "bigger than" / "less than" with a text input, so i can filter out every item that is more expensive than 10$?

**Comment by ly525** [comment]
sorry about this, we do not support filter expression with text field util this moment, but it's a great feature to support filter expression (include regex).

**Comment by ly525** [comment]
you can add a text field above the table to implement the filter function yourself temporarily and and a dropdown menu to specify the column

**Comment by ly525** [comment]
TODO
>  Demo from google adwords

# 1 
<img width="40%" src="https://user-images.githubusercontent.com/12668546/51604529-01cf9b00-1f48-11e9-9404-5b42d3dfbfc4.png">


<hr>

# 2
<img width="40%" src="https://user-images.githubusercontent.com/12668546/51604491-ecf30780-1f47-11e9-8fcb-b65dc9589a90.png">

**Comment by stefnats** [comment]
Yes, that's what i meant 👍

**Comment by huangshuwei** [comment]
The new version has solved this problem. [filter custom](http://doc.huangsw.com/vue-easytable/#/en/doc/table/header-filter-custom)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)

**Comment by stefnats** [comment]
@huangshuwei congrats on the new version. Noted!
