### ISSUE TITLE
使用footer时列冻结问题

### ISSUE THREAD

**Issue by IIIThSoul** [Happy-Coding-Clans/vue-easytable#263]
使用footer时，必须拖动footer部分，未冻结部分才可以滚动，请问可以推动非冻结的数据列来拖动展示吗？

**Comment by huangshuwei** [comment]
The new version has solved this problem. [footer column fixed doc](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/footer-summary?anchor=footer-jie-he-gu-ding-lie)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
