### ISSUE TITLE
关于行列合并

### ISSUE THREAD

**Issue by qianfangyuan** [Happy-Coding-Clans/vue-easytable#264]
cell-merge 的方式是通过每一行调用一次函数？
我的数据合并是根据数据中有相同的进行合并的(格式不固定)，怎样合并只需要计算一次即，调用一次 cell-merge即可。
能否提供一个只需要调用一次的api ？

**Comment by kevin2y** [comment]
我也在考虑依据数据进行“行合并”。现有的cell-merge机制也认为也是可取的。只差怎么取到其他行的数据来判断最终是合并多少行，我准备试试自己修改代码

**Comment by kevin2y** [comment]
查看代码，似乎很多地方有调用cellMerge方法，官方的其中一个例子，8行8列的数据表，调用了192次的cellMerge

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
