### ISSUE TITLE
关于用footer做统计的问题

### ISSUE THREAD

**Issue by AiHaoChen** [Happy-Coding-Clans/vue-easytable#265]
> footer不能行、列合并，希望能添加footer的colSpan、rowSpan。
比如您给的footer做汇总的demo，我现在有需求，footer的最小值这个单元格要合并姓名和数值1这两列。

**Comment by ly525** [comment]
可否提供一些参考事例 或者 实际的需求场景说明？

**Comment by huangshuwei** [comment]
The new version has solved this problem. [footer cell span](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/footer-summary?anchor=footer-lie-he-bing)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
