### ISSUE TITLE
可编辑单元格TAB键切换

### ISSUE THREAD

**Issue by wangyu3c** [Happy-Coding-Clans/vue-easytable#272]
首先很感谢大神能写出这样的表格组件，使用的过程中发现了有一点不便，现在激活可编辑单元格的方式是通过单击鼠标左键，当一行有较多可编辑单元格时，需要编辑前都需要点击一下鼠标左键，不太方便，能否支持TAB键切换待编辑的单元格呢

**Comment by ly525** [comment]
@wangyu3c 考虑支持，非常好的建议，感谢

**Comment by mrgulc** [comment]
需要这个功能哦！
