### ISSUE TITLE
请问，进入单元格编辑时，可否将内容设为全部选中状态？

### ISSUE THREAD

**Issue by gitMissLi** [Happy-Coding-Clans/vue-easytable#273]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能**
**Is your feature request related to a problem? Please describe.**

**描述下，你希望得到的什么解决方案 **
**Describe the solution you'd like**

**是否有不错的替代方案**
**Describe alternatives you've considered**

**附加信息**
**Additional context**

**Comment by ly525** [comment]
可否提供示意图 或者 更详细的说明？
