### ISSUE TITLE
IE浏览器报错，项目运行不了。

### ISSUE THREAD

**Issue by CyberJerry2019** [Happy-Coding-Clans/vue-easytable#278]
引用easy table后在ie环境下项目跑不起来，注释掉easytable的引用后就没问题。首先是报data缺少 ':'，然后是报method里面的方法写的不规范，得加上function，加上之后继续报错，说是语法错误，识别不了箭头函数，请大佬指点一下问题在哪。vue和easytable都是最新版的，ie版本是11.

**Comment by ly525** [comment]
可否提供一个可以复现的例子，比如jsfiddle

**Comment by CyberJerry2019** [comment]
![1](https://user-images.githubusercontent.com/48911622/54964294-e106de80-4fa6-11e9-987f-d007b8cc6f65.JPG)
![2](https://user-images.githubusercontent.com/48911622/54964360-1f9c9900-4fa7-11e9-982c-cc989082feee.JPG)
![3](https://user-images.githubusercontent.com/48911622/54964366-24f9e380-4fa7-11e9-9e4d-2fca36180136.JPG)
jsfiddle 没用过，不太好把源码搬上去。

**Comment by hcwhan** [comment]
我的也是 看了下 编译后的代码 还是es6 语法的 所以报错了

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
