### ISSUE TITLE
AMD模块规范的加载器无法使用

### ISSUE THREAD

**Issue by uutool** [Happy-Coding-Clans/vue-easytable#279]
如requirejs不能加载使用该包，使用webpack设置output.libraryTarget=amd后重新打包也无法使用，报错：
[Vue warn]: Failed to mount component: template or render function not defined.

**Comment by MillerRen** [comment]
`require(['vue-easytable'], function (module) {
  console.log(module.default) // 注意这个default
})`

**Comment by afdr** [comment]
你现在用require引入可以使用了吗? 我也用require引入的, module直接是undefined

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
