### ISSUE TITLE
禁用的多选框可以点击取消

### ISSUE THREAD

**Issue by jimixy** [Happy-Coding-Clans/vue-easytable#280]
在高级多选功能的示例中：https://jsfiddle.net/k851spum/1/ 。第二条和第三条数据被禁止勾选了，但操作中发现还是可以勾选的。浏览器版本Chrome/72.0.3626.121

**Comment by jimixy** [comment]
另外可不可以加上不用多选的判断，就是表格title不用多选框，直接显示Title字段

**Comment by ly525** [comment]
好的，我来看下

**Comment by fengkuang0307** [comment]
问题解决了吗？

**Comment by huangshuwei** [comment]
The new version has solved this problem.  [row checkbox doc](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/row-checkbox)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
