### ISSUE TITLE
自定义列不显示

### ISSUE THREAD

**Issue by nbeezander** [Happy-Coding-Clans/vue-easytable#281]
windows 系统， vue 2.6.6 ； 直接复制的自定义列里引导教程的代码，但是不能正确显示。

浏览器查看元素，显示如下
```
<span>
<!--function(t,n,r,i){return hn(e,t,n,r,i,!0)}-->
</span>
```

**Comment by ly525** [comment]
麻烦提供下浏览器的相关信息

**Comment by nbeezander** [comment]
chrome 73

**Comment by liweijian1** [comment]
解决了吗，遇到一样的问题

**Comment by tongtongking** [comment]
遇到自定义列高级用法不显示，并且还报一下错误：[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
最终通过 https://stackoverflow.com/questions/47332728/you-are-using-the-runtime-only-build-of-vue-where-the-template-compiler-is-not-a?rq=1
解决，也就是 在vue.config.js文件中找到configureWebpack并增加'vue$': 'vue/dist/vue.esm.js'：
configureWebpack: {
    resolve: {
      alias: {
        'vue$': 'vue/dist/vue.esm.js'
      }
    }
  }

**Comment by huangshuwei** [comment]
The new version has solved this problem. [cell custom doc](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/cell-custom)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
