### ISSUE TITLE
容器div宽度发生变化， 表格没有跟随变化。  有没有resize可以重置一下。急！

### ISSUE THREAD

**Issue by raymondZhong** [Happy-Coding-Clans/vue-easytable#282]
容器div宽度发生变化， 表格没有跟随变化。  有没有resize可以重置一下。急！
![image](https://user-images.githubusercontent.com/1297621/55549447-75401680-5708-11e9-9761-712497ebac40.png)

API有个 resize方法。  请问如何调用。

**Comment by Mr-wang007s** [comment]
踩坑+1， 您找到解决方案了？

**Comment by Live-forever** [comment]
采坑+1, 
![image](https://user-images.githubusercontent.com/30582050/57678116-1badfe80-765b-11e9-9508-5c3fe8102657.png)

**Comment by Live-forever** [comment]
调用了 resize 方法 效果 不是很好, 还是有问题,  求解决方案

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
