### ISSUE TITLE
height 通过计算属性得来的，数值变后，dom结构中的内联样式高度值没有改变，导致视图没有生效

### ISSUE THREAD

**Issue by xueqiliu** [Happy-Coding-Clans/vue-easytable#284]
**height 通过计算属性得来的 **
 例如，:height="proxy_height" return 的值是300
但是dom结构中的内联样式上的height值还是初始化的246px
![image](https://user-images.githubusercontent.com/8528958/55713915-3b328580-5a24-11e9-9ed7-2abf253e6e8f.png)
使用了resize() 也不起作用
希望可以得到帮助

**Comment by ly525** [comment]
@xueqiliu 收到，应该是源码中没有watch height 导致的，我来看下。

**Comment by xsdream** [comment]
请问这个问题解决了吗，我也遇到了

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
