### ISSUE TITLE
前端动态删除行后，数据刷新问题

### ISSUE THREAD

**Issue by zhuochengs** [Happy-Coding-Clans/vue-easytable#285]
您好，很高兴使用您的开源组件，我们目前是企业内部系统结合element ui+easytable来完成多行明细编辑的功能，目前发现一个问题，如果是数据列是自己写的可编辑组件（el-input, el-select等），在删除某一行时，发现数据刷新异常，举例，一共10行，手动删除第6 行，数据跟踪检测确实是第六行被删除了，但是渲染的效果是第十行被删除了，经过多种尝试发现除了 this.$nextTrick() 这样重绘整个表格的方式，没有合适的方式，请问有优化方案吗

**Comment by ly525** [comment]
@zhuochengs 玛法提供下可以复现的例子吧，或者代码仓库

**Comment by zhuochengs** [comment]
能否加一下好友，我有一些优化方面的想请教下，我的QQ624753698

**Comment by ly525** [comment]
@zhuochengs 可以到 README 中提到的 discord 中讨论，也是一个即时聊天工具，你可以在相关的频道直接提问就好了

**Comment by zhuochengs** [comment]
您好，ly525，我已经在discord中提问了哈，麻烦看一下，感谢！~~~

**Comment by ly525** [comment]
好的，您也可以添加readme里面的作者的微信。discord 我去装一个app，最近一段时间太忙了，不好意思

**Comment by zhuochengs** [comment]
@ly525 我都已经加了好几次作者的微信了，从来没有加过我~~~~~

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
