### ISSUE TITLE
css完全自定义

### ISSUE THREAD

**Issue by xiejinhe** [Happy-Coding-Clans/vue-easytable#286]
组件功能很全面，完全符合我的需求。css样式不符合，我可以在不用改js的情况完全替换css样式吧？

**Comment by supervons** [comment]
你可以在页面 style中 增加scoped，然后组件的样式使用div >>> .title-cell-class-title来进行穿透，这样既改变了当前页面的样式，也对其他引用该组件的页面的样式没有任何污染。

**Comment by huangshuwei** [comment]
The new version has solved this problem. [theme custom](http://doc.huangsw.com/vue-easytable/#/en/doc/theme)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
