### ISSUE TITLE
单选功能

### ISSUE THREAD

**Issue by webzlj** [Happy-Coding-Clans/vue-easytable#288]
1 没有单选功能，用select-change来判断，点击一个后，继续选中第二个，人为提示只能选中一条，但是第二个的样式也还是变为选中的状态；2 在只能单选的情况下，全选功能的样式要如何修改

**Comment by huangshuwei** [comment]
The new version has solved this problem. [row radio doc](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/row-radio)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
