### ISSUE TITLE
排序中sortChange（params）{}里面应该怎么写？

### ISSUE THREAD

**Issue by huangwenlong528** [Happy-Coding-Clans/vue-easytable#289]
官方文档上写的是在sortChange（params）{}里面重新请求一下数据就行了，但是我直接重新请求数据好像是不起作用的，想请大神帮忙讲解一下。

**Comment by supervons** [comment]
![image](https://user-images.githubusercontent.com/31637849/57189105-e576cd80-6f3c-11e9-860e-0f2955d00efe.png)
你可以参考一下，需要对其进行排序返回正数，负数或者0

**Comment by huangwenlong528** [comment]
> ![图片](https://user-images.githubusercontent.com/31637849/57189105-e576cd80-6f3c-11e9-860e-0f2955d00efe.png)
> 你可以参考一下，需要对其进行排序返回正数，负数或者0

多谢您了

**Comment by huangwenlong528** [comment]
------------------ 原始邮件 ------------------
发件人: "supervons"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 中午1:52
收件人: "huangshuwei/vue-easytable"<vue-easytable@noreply.github.com>;
抄送: "1773871775"<1773871775@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [huangshuwei/vue-easytable] 排序中sortChange（params）{}里面应该怎么写？ (#289)





 你可以参考一下，需要对其进行排序返回正数，负数或者0

**Comment by supervons** [comment]
邮箱发我，我发给你。

**Comment by huangwenlong528** [comment]
你好！那个排序的我已经弄好了，不过还是很感谢您！如果您方便的话发给我一份可以吗？我觉得自己写的比较麻烦了。




------------------ 原始邮件 ------------------
发件人: "supervons"<notifications@github.com>;
发送时间: 2019年5月12日(星期天) 晚上11:06
收件人: "huangshuwei/vue-easytable"<vue-easytable@noreply.github.com>;
抄送: "1773871775"<1773871775@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [huangshuwei/vue-easytable] 排序中sortChange（params）{}里面应该怎么写？ (#289)




邮箱发我，我发给你。

**Comment by huangshuwei** [comment]
The new version has solved this problem. [sort doc](http://doc.huangsw.com/vue-easytable/#/en/doc/table/header-sort)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
