### ISSUE TITLE
表格Title传入一个自定义组件

### ISSUE THREAD

**Issue by supervons** [Happy-Coding-Clans/vue-easytable#290]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能**
**Is your feature request related to a problem? Please describe.**
在目前的场景中，想自定义表头，比如在表头旁边增加一个搜索框，来达到自定义单列搜索的效果，或者是在title旁边增加一个tips。
**描述下，你希望得到的什么解决方案 **
**Describe the solution you'd like**
传入的columns中的title可以传入一个组件。
**是否有不错的替代方案**
**Describe alternatives you've considered**
无
**附加信息**
**Additional context**

**Comment by tanxuxu** [comment]
遇到同样的问题，请问还更新吗，需要等多久

**Comment by adoniscyz** [comment]
同样的问题, 可以支持传入自定义组件吗

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
