### ISSUE TITLE
Add a test framework and/or a CI

### ISSUE THREAD

**Issue by ecaramba** [Happy-Coding-Clans/vue-easytable#293]
**这个新特性和一个问题相关吗？简单描述下，比如我什么场景下，需要解决什么问题，发现表格不支持这个功能**
**Is your feature request related to a problem? Please describe.**
I want to make some contributions to this project, but I want to prevent things from breaking down and losing quality.

**描述下，你希望得到的什么解决方案 **
**Describe the solution you'd like**
In the official vue page, has a guide at
- https://vuejs.org/v2/cookbook/unit-testing-vue-components.html 
- and https://vue-test-utils.vuejs.org/guides/#getting-started

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
