### ISSUE TITLE
最后一列rowSpan的话，前面的列右分隔线会消失

### ISSUE THREAD

**Issue by greatflag** [Happy-Coding-Clans/vue-easytable#295]
最右的列跨行的话，会导致
`.v-table-rightview-special-border td:last-child .v-table-body-cell {
    border-right-width: 0 !important
}`
在前面的列上生效

**Comment by huangshuwei** [comment]
The new version has solved this problem. [cell span](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/cell-span)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
