### ISSUE TITLE
一个页面两个表格，会导致有时候表格渲染的时候宽度无限大，导致页面显示不出来，怎么解决？

### ISSUE THREAD

**Issue by yangzm0618** [Happy-Coding-Clans/vue-easytable#296]
**Describe the bug 仔细描述这个 Bug **
简明扼要描述一下 这个 Bug

**To Reproduce 复现步骤**

**Expected behavior 期待的行为**
 简明扼要描述下 你期待的正确结果是什么？

**Screenshots**
如果可以的话，可以添加截图来描述下 Bug

**添加 浏览器、包、Node 版本信息**
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

** Package **
 - Package Version [e.g. 1.7.2]
 - Node Version [e.g 10.0]

**额外信息，没有的话，可以删除**
**Additional context**

**Comment by xinxingu** [comment]
我也遇到这个问题，请问后来有解决吗

**Comment by huangshuwei** [comment]
The new version has solved this problem.  [virtual scroll doc](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/virtual-scroll)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
