### ISSUE TITLE
如何在requirejs下面加载和使用

### ISSUE THREAD

**Issue by sweajie** [Happy-Coding-Clans/vue-easytable#298]
**现有的项目是requirejs写的 , vue也是requirejs加载的**
在使用requirejs引入模块的时候 , 提示 

> Unknown custom element: &lt;v-table&gt; - did you register the component correctly? For recursive components, make sure to provide the "name" option.

[http://www.c88.in/debug/index/esay_table](url) 
我做了个测试地址可以看这里

**Comment by TroyIrvo** [comment]
同问这个问题，我之前测试也发现umd在requirejs无法正确使用。

**Comment by HyouImport** [comment]
同问，有解决办法没？

**Comment by uutool** [comment]
同问
