### ISSUE TITLE
dependencies与devDependencies傻傻分不清,vue-router放错位置,导致引用vue-easytable后项目出错

### ISSUE THREAD

**Issue by yangdan8** [Happy-Coding-Clans/vue-easytable#300]
**Describe the bug 仔细描述这个 Bug **
简明扼要描述一下 这个 Bug
dependencies与devDependencies傻傻分不清,vue-router放错位置,导致引用vue-easytable后项目出错

**To Reproduce 复现步骤**

**Expected behavior 期待的行为**
 简明扼要描述下 你期待的正确结果是什么？

**Screenshots**
如果可以的话，可以添加截图来描述下 Bug

**添加 浏览器、包、Node 版本信息**
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

** Package **
 - Package Version [e.g. 1.7.2]
 - Node Version [e.g 10.0]

**额外信息，没有的话，可以删除**
**Additional context**

**Comment by xiaogaofudao** [comment]
https://github.com/huangshuwei/vue-easytable/issues/335

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
