### ISSUE TITLE
实时超大列表实现方案

### ISSUE THREAD

**Issue by zlwen** [Happy-Coding-Clans/vue-easytable#305]
我这里有个需求，表格里的内容是实时通过websocket获取，数据量非常大，不知有何好的解决方案

**Comment by xlz26296** [comment]
@zlwen  大数据量你可以参考这个虚拟滚动 https://xuliangzhan.github.io/vxe-table/#/table/scroll/scroll

**Comment by huangshuwei** [comment]
The new version has solved this problem. [virtual scroll doc](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/virtual-scroll)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
