### ISSUE TITLE
排序的时候不知道当前选中的是哪一列？

### ISSUE THREAD

**Issue by xuzz123** [Happy-Coding-Clans/vue-easytable#306]
排序的时候不知道当前选中的是哪一列？
sort-change里面没有指明当前排序的是哪一列

**Comment by huangshuwei** [comment]
The new version has solved this problem. [sort doc](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/header-sort)

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
