### ISSUE TITLE
在element-ui的el-tabs里面第一次显示空白，后面正常

### ISSUE THREAD

**Issue by huashenyun** [Happy-Coding-Clans/vue-easytable#309]
<el-dialog>
      <el-tabs type="border-card">
          <el-tab-pane>
            <span slot="label"><i class="el-icon-edit" /> 资料</span>
            <v-table
              is-horizontal-resize
              style="width:100%"
              :columns="columns"
              :table-data="datas"
              row-hover-color="#eee"
              row-click-color="#edf7ff"
              :cell-edit-done="cellEditDone"
            />
          </el-tab-pane>
          <el-tab-pane>
            <span slot="label"><i class="el-icon-date" /> 2</span>
          </el-tab-pane>
        </el-tabs>
</el-dialog>

这种对话框第一次不显示，后面点击才显示

**Comment by openliu** [comment]
<el-dialog :title="titile" :visible.sync="dialogFormVisible">
        <el-tabs type="border-card">
          <el-tab-pane>
            <span slot="label"><i class="el-icon-edit" /> 11111</span>

            <v-table
              is-horizontal-resize
              style="width:100%"
              :columns="columns"
              :table-data="temp.products"
              row-hover-color="#eee"
              row-click-color="#edf7ff"
              :cell-edit-done="cellEditDone"
            />
          </el-tab-pane>

          <el-tab-pane>
            <span slot="label"><i class="el-icon-date" /> 22222</span>
            22222
          </el-tab-pane>
        </el-tabs>

    </el-dialog>

**Comment by openliu** [comment]
这种格式的时候才会出现

**Comment by LoneKingCode** [comment]
给v-table组件加上属性v-if="activeName=='second'"， v-if的条件是 显示指定tab时才显示table，这样没问题，可以也把table放第二个tab然后这样试试

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
