### ISSUE TITLE
移动端横向拖动问题

### ISSUE THREAD

**Issue by wtulee** [Happy-Coding-Clans/vue-easytable#314]
感谢作者提供这么好用的表格组件。在使用中将表格用在移动端，发现垂直滚动没有问题；水平滚动只能点击滚动条次才能左右移动，拖动方式无效。不知道是不是哪里配置的问题，特来请教。代码如下：
<div id="app">
			<div>
				<v-table 
					:height='360' 
					:min-height='360' 
					:columns="columns" 
					:table-data="tableData" 
					is-vertical-resize
					is-horizontal-resize
					style="width:100%" 
					:vertical-resize-offset='10' 
					row-hover-color="#FFF0F5" 
					row-click-color="EEA9B8">
				 </v-table>
		</div>

		<script type="text/javascript">
			var vm = new Vue({
				el: '#app',
				data: function() {
					return {
						columns: [
							{field: 'row', title: '行', width: 35, titleAlign: 'center', columnAlign: 'center',isFrozen: true },
							{field: 'Status',title: '状态',width: 60,titleAlign: 'center',columnAlign: 'center' },
							{field: 'RequestTime',title: '时间',width: 60,titleAlign: 'center',columnAlign: 'center' },
							{field: 'MaterialName',title: '物料名称',width: 160,titleAlign: 'center',columnAlign: 'left'},
							{field: 'RequestUserName',title: '用户',width: 75,titleAlign: 'center',columnAlign: 'left'},
							{field: 'MaterialCode',title: '物料号',width: 110,titleAlign: 'center',columnAlign: 'center'}
						],
						tableData: [
							{ row: 0, Status: '已拣货', RequestTime: '2019-08-29 08:00:00', MaterialName:'xxx', RequestUserName: 'xxx', MaterialCode:'xxx'},
							{ row: 0, Status: '已拣货', RequestTime: '2019-08-29 08:00:00', MaterialName:'xxx', RequestUserName: 'xxx', MaterialCode:'xxx'},
							{ row: 0, Status: '已拣货', RequestTime: '2019-08-29 08:00:00', MaterialName:'xxx', RequestUserName: 'xxx', MaterialCode:'xxx'},
							{ row: 0, Status: '已拣货', RequestTime: '2019-08-29 08:00:00', MaterialName:'xxx', RequestUserName: 'xxx', MaterialCode:'xxx'},
							{ row: 0, Status: '已拣货', RequestTime: '2019-08-29 08:00:00', MaterialName:'xxx', RequestUserName: 'xxx', MaterialCode:'xxx'},
							{ row: 0, Status: '已拣货', RequestTime: '2019-08-29 08:00:00', MaterialName:'xxx', RequestUserName: 'xxx', MaterialCode:'xxx'},
							{ row: 0, Status: '已拣货', RequestTime: '2019-08-29 08:00:00', MaterialName:'xxx', RequestUserName: 'xxx', MaterialCode:'xxx'},
							{ row: 0, Status: '已拣货', RequestTime: '2019-08-29 08:00:00', MaterialName:'xxx', RequestUserName: 'xxx', MaterialCode:'xxx'},
							{ row: 0, Status: '已拣货', RequestTime: '2019-08-29 08:00:00', MaterialName:'xxx', RequestUserName: 'xxx', MaterialCode:'xxx'},
							{ row: 0, Status: '已拣货', RequestTime: '2019-08-29 08:00:00', MaterialName:'xxx', RequestUserName: 'xxx', MaterialCode:'xxx'},
						],
						
					}
				}
			});
		</script>
效果图：
![image](https://user-images.githubusercontent.com/31568993/63941338-00e28700-ca9e-11e9-81e4-78d345897cac.png)

**Comment by wtulee** [comment]
<div id="app">
			<div>
				<v-table 
					:height='360' 
					:min-height='360' 
					:columns="columns" 
					:table-data="tableData" 
					is-vertical-resize
					is-horizontal-resize
					style="width:100%" 
					:vertical-resize-offset='10' 
					row-hover-color="#FFF0F5" 
					row-click-color="EEA9B8">
				 </v-table>
		</div>

**Comment by wtulee** [comment]
配置项怎么显示不出来，补上：

				<v-table 
					:height='360' 
					:min-height='360' 
					:columns="columns" 
					:table-data="tableData" 
					is-vertical-resize
					is-horizontal-resize
					style="width:100%" 
					:vertical-resize-offset='10' 
					row-hover-color="#FFF0F5" 
					row-click-color="EEA9B8">
				 </v-table>

**Comment by wtulee** [comment]
配置项怎么显示提交不上去，补上：
				<v-table 
					:height='360' 
					:min-height='360' 
					:columns="columns" 
					:table-data="tableData" 
					is-vertical-resize
					is-horizontal-resize
					style="width:100%" 
					:vertical-resize-offset='10' 
					row-hover-color="#FFF0F5" 
					row-click-color="EEA9B8">
				 </v-table>

**Comment by zonggg** [comment]
同样遇到了这个问题，第一次横向滚动时，不生效.

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
