### ISSUE TITLE
单元格编辑

### ISSUE THREAD

**Issue by shuliangfu** [Happy-Coding-Clans/vue-easytable#316]
单元格编辑是单击，怎么样设置双击时进行编辑单元格？单击感觉不太好，谢谢

**Comment by FUHUALUN** [comment]
官方API中有写
row-click | 行单击回调 | Function({rowIndex, rowData, column}) 
row-dblclick | 行双击回调 | Function({rowIndex, rowData, column}) 
title-click | 表头单元格单击回调 | Function({title,field}) 
title-dblclick | 表头单元格双击回调 | Function({title,field}) 
row-mouse-enter | 鼠标进入表体行的回调 | Function({rowIndex})
row-mouse-leave | 鼠标离开表体行的回调 | Function({rowIndex}) 
如果单击单元格是想触发函数，可在cell-edit-done中设置函数名称

**Comment by shuliangfu** [comment]
> 官方API中有写
> row-click | 行单击回调 | Function({rowIndex, rowData, column})
> row-dblclick | 行双击回调 | Function({rowIndex, rowData, column})
> title-click | 表头单元格单击回调 | Function({title,field})
> title-dblclick | 表头单元格双击回调 | Function({title,field})
> row-mouse-enter | 鼠标进入表体行的回调 | Function({rowIndex})
> row-mouse-leave | 鼠标离开表体行的回调 | Function({rowIndex})
> 如果单击单元格是想触发函数，可在cell-edit-done中设置函数名称

感觉不太对，设置你上面提的方法，怎么跟idEdit绑定？

isEdit
--




isEdit
--



isEdit
--




isEdit
--

**Comment by FUHUALUN** [comment]
idEit设置成true，合并单元格的话用content，不合并用title都可以啊

**Comment by shuliangfu** [comment]
> idEit设置成true，合并单元格的话用content，不合并用title都可以啊

不合并单元格，我只是把想isEdit=true,编辑单元格，因为默认是单就编辑，我感觉单击编辑不太好，有时候不小心点击了一下就变成编辑状态了，要是不小心又输入了东西，那就什么时候改了内容都不知道，所以我想把默认的单击编辑单元格改成双击，用你上面说的row-dblclick我不知道怎么绑定绑架单元格
