### ISSUE TITLE
翻页功能问题

### ISSUE THREAD

**Issue by BruceCobb** [Happy-Coding-Clans/vue-easytable#333]
我的Vue页面有很多表格，在使用表格翻页功能的时候，我需要把每个页面的数据传递给 getTableData() 函数进行翻页，但是我不知道如何把循环出料的item 变量传递给 pageChange 和 pageSizeChange，因为他们好像是您已经写好的。

**Comment by huangshuwei** [comment]
请使用新版本。[参考分页示例](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/pagination)
