### ISSUE TITLE
请问是否支持属性按列展开，左侧第一列是表头

### ISSUE THREAD

**Issue by Dsev7n** [Happy-Coding-Clans/vue-easytable#342]
现在的表格是第一行是表头，希望能增加第一列当表头的属性。每一列是一个item，按列展开。

**附加信息**
![image](https://user-images.githubusercontent.com/30361645/94354717-642f5600-00b0-11eb-8bd0-04447d0c41db.png)

**Comment by huangshuwei** [comment]
目前不支持，需要自己把数据做一个转置

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)

**Comment by yituwangpeng** [comment]
在version2.0中，怎么实现第一列做表头呢？API文档中没有看到方法～～
