### ISSUE TITLE
optional improvement for event-listener demos in documentation 关于文档里 自定义事件tag demo的（可选）建议

### ISSUE THREAD

**Issue by MoShian90s** [Happy-Coding-Clans/vue-easytable#349]
**Describe the bug 仔细描述这个 Bug **

[Zh-Documentation](http://doc.huangsw.com/vue-easytable/#/zh/doc/table/event-custom)

![image](https://user-images.githubusercontent.com/24494673/106277602-4ece6200-6231-11eb-816a-5fd097dff567.png)

**Expected behavior 期待的行为**

`:eventCustomOption="eventCustomOption"` 
you had better modify it to the next part
`:event-custom-option="eventCustomOption"`
in my view, the latter is more friendly to novices, especially for youngsters such as me. besides, it keeps the style with other attributes: ':table-data' and so on

**Comment by huangshuwei** [comment]
Yes,You are right. It's a matter of naming conventions. I'll change it to hyphenation

**Comment by huangshuwei** [comment]
Document updated. Please try again
