### ISSUE TITLE
Cannot access data from object data

### ISSUE THREAD

**Issue by truongnguyengithub** [Happy-Coding-Clans/vue-easytable#354]
1. Cannot access data from object data?
2. How to show content if table data is null or not any item?

![2021-02-02_231644](https://user-images.githubusercontent.com/42446645/106629103-13bf8c00-65ad-11eb-853e-d854e849e63a.png)

![2021-02-02_231927](https://user-images.githubusercontent.com/42446645/106629153-21751180-65ad-11eb-8d47-5c62b9001df1.png)

**Comment by huangshuwei** [comment]
The pagination component and the table component are separate.

[how to use pagination comp](http://doc.huangsw.com/vue-easytable/#/en/doc/base/pagination)
