### ISSUE TITLE
[Bug Report] Table jittering when scrolling.

### ISSUE THREAD

**Issue by gokigoks** [Happy-Coding-Clans/vue-easytable#355]
I am opening an issue for
vue-easytable

### Issue Type
Bug

###  Issue Title
Table jittering when scrolling.

### library Version
1.7.2

### Vue Type
2.2.6

### Browser Type
Chrome  88.0.4324.96

### System version
Windows

### Reproduction url
Please see the steps to reproduce.

### Step to reproduce
Not sure how to reproduce this issue as this started happening without notice. 

### What is expected?
This should be smooth to scroll.

### What is actually happening?
Jittering when being scrolled.

I apologize if I have minimal details for the issue. A helpful detail might be that we are 
https://user-images.githubusercontent.com/10005383/106633783-170d4480-65ba-11eb-876f-15fbc195a525.mov

**Comment by huangshuwei** [comment]
The new version has resolve this problem.

[Column fixed](http://doc.huangsw.com/vue-easytable/#/en/doc/table/column-fixed?anchor=fixed-left-and-right-columns) example in new version.

**Comment by gokigoks** [comment]
Thank you for the response and thank you for the help!
