### ISSUE TITLE
Column fixed error UI when fixed:"left" with checkbox

### ISSUE THREAD

**Issue by truongnguyengithub** [Happy-Coding-Clans/vue-easytable#362]
http://doc.huangsw.com/vue-easytable/#/en/doc/table/column-fixed

![image](https://user-images.githubusercontent.com/42446645/109458902-4ebfbd00-7a90-11eb-9a72-0adbff3ba928.png)

**Comment by huangshuwei** [comment]
- Please provide a link by forking CodeSandbox. (codepen or jsfiddle are not recommended. They are not friendly to JSX support.)

**Comment by truongnguyengithub** [comment]
> * Please provide a link by forking CodeSandbox. (codepen or jsfiddle are not recommended. They are not friendly to JSX support.)
> * This is [issue template](http://doc.huangsw.com/issue-template-generater/#/en)

**This is an example error UI when fixed the right column and using the checkbox**
https://codesandbox.io/s/practical-sun-oc0w8?file=/Example.vue

**Comment by huangshuwei** [comment]
This is a modified example:
https://codesandbox.io/s/ecstatic-oskar-zzl0r?file=/Example.vue

Two points to pay attention to
1、Row checkbox need `checkboxOptipon` prop to handle check row event
2、Need `rowKeyFieldName` prop to record the row you selected

refer to [Row checkbox example](http://doc.huangsw.com/vue-easytable/#/en/doc/table/row-checkbox)

**Comment by truongnguyengithub** [comment]
Thank you so much 👍

**Comment by huangshuwei** [comment]
you are welcome
