### ISSUE TITLE
引入文件都报错 不能正常使用

### ISSUE THREAD

**Issue by lance0923** [Happy-Coding-Clans/vue-easytable#363]
ERROR in ./node_modules/vue-easytable/libs/main.js
Module parse failed: Unexpected token (1:42243)
You may need an appropriate loader to handle this file type.

我只写了
import Vueeasytable from 'vue-easytable'就开始报错了

**Comment by huangshuwei** [comment]
假设你使用的最新版本 2.4.0 可参考 codesandbox 示例：
https://codesandbox.io/s/vue-easytable240-example-forked-z92i5

**Comment by FE-Mars** [comment]
我也有同样的错误

**Comment by huangshuwei** [comment]
@FE-Mars 
麻烦提供重现步骤，谢谢

**Comment by FE-Mars** [comment]
> @FE-Mars
> 麻烦提供重现步骤，谢谢

就是单纯的引入
`import { VeTable } from "vue-easytable";`

**Comment by huangshuwei** [comment]
The new version fixes this problem:
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/2.5.3
