### ISSUE TITLE
[Bug Report] 在苹果手机上，表格滑动会飘动

### ISSUE THREAD

**Issue by WytheChan** [Happy-Coding-Clans/vue-easytable#364]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
在苹果手机上，表格滑动会飘动

### 仓库版本
2.4.0

### Vue 版本
2.6.12

### 浏览器
微信浏览器 8.0.2

### 系统类型
IOS 14.2

### 重现链接
<a href="http://test.houjt.cn/userproject/cjytest/demo/img/ios_scroll.mp4" target="_blank">http://test.houjt.cn/userproject/cjytest/demo/img/ios_scroll.mp4</a>

### 重现步骤
设置了固定列和固定表头，在表格滑动的时候由于苹果手机的滑动惯性，整个表格在滑动的时候会飘动，体验不好。用了虚拟滚动也有一样的问题。

### 期望的结果是什么？
表格在滑动的时候能稳定流畅

### 实际的结果是什么？
希望改善苹果手机的表格滑动体验

**Comment by huangshuwei** [comment]
1、手机端不建议使用，iOS 设备由于回弹问题导致的表格撕裂
2、手机端的表格组件已经在开发了，不过发布时间待定

**Comment by WytheChan** [comment]
明白了，感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Huang ***@***.***&gt;; 
发送时间: 2021年3月15日(星期一) 下午5:08
收件人: ***@***.***&gt;; 
抄送: "嘎嘎 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Happy-Coding-Clans/vue-easytable] [Bug Report] 在苹果手机上，表格滑动会飘动 (#364)





 
1、手机端不建议使用，iOS 设备由于回弹问题导致的表格撕裂
 2、手机端的表格组件已经在开发了，不过发布时间待定

**Comment by YJKZHUZHU** [comment]
还会解决这个问题吗
