### ISSUE TITLE
themes-base文件包改成什么了，我试过theme-dark和theme-default都报Module parse failed: Unexpected token (1:42333) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by soroslinlin** [Happy-Coding-Clans/vue-easytable#366]

**Comment by huangshuwei** [comment]
完整引入：
```
import Vue from "vue";
// 引入样式
import "vue-easytable/libs/theme-default/index.css";
// 引入组件库
import VueEasytable from "vue-easytable";

Vue.use(VueEasytable);

new Vue({
  el: "#app",
  render: (h) => h(App),
});
```

具体参考快速开始文档：
http://doc.huangsw.com/vue-easytable/#/zh/doc/start

**Comment by soroslinlin** [comment]
试过了那个，具体错误是这样的：
 ERROR  Failed to compile with 1 errors

                                                     16:12:41

 error  in ./node_modules/vue-easytable/libs/main.js

Module parse failed: Unexpected token (1:42333)
You may need an appropriate loader to handle this file type.
[image: photo_2021-04-08_16-14-23.jpg]

Huang ShuWei ***@***.***> 于2021年4月8日周四 下午4:08写道：

**Comment by huangshuwei** [comment]
用的哪个版本

**Comment by huangshuwei** [comment]
完整使用案例：https://codesandbox.io/s/vue-easytable241-example-forked-96thb

**Comment by soroslinlin** [comment]
是最新版。yum装的，可能其他地方的版本不对，我先看看吧，谢谢你

Huang ShuWei ***@***.***> 于2021年4月8日周四 下午4:26写道：
