### ISSUE TITLE
vue-cli中使用easytable1.7.2版本时，自定义列如何添加？

### ISSUE THREAD

**Issue by chuliul** [Happy-Coding-Clans/vue-easytable#367]
将Vue.component('table-operation',{}）的写法换成重新创建一个vue文件，并import TestCom from '../components/Test.vue',设置componentName:TestCom，用vue调试工具在浏览器里看到了columns中componentName:TestCom 。testCom为一个组件。但是表格里面没有渲染成功，文字和点击事件都未生效。想问一下正确的使用方法是什么？

**Comment by huangshuwei** [comment]
强烈推荐使用最新版本，支持 vue2.x。自定义列实现更简单，其他功能也做了优化

**Comment by chuliul** [comment]
哎。。。最开始安装的2.x，然后和我们公司做的一个基于vue的一个平台冲突了，公司平台是webpack3和babel6，引入vue-easyTable后会报错，开发平台的同事说问题不是很好解决，变动很大，建议我用1.x的。但是在1.x的使用过程中发现了刚刚这个问题。2.x确实好用，我功能都写完了，最后被告知无法使用2.x

**Comment by huangshuwei** [comment]
> 公司平台是webpack3和babel6，引入vue-easyTable后会报错

也可能是vue 的版本过低，vue 版本升级到vue2.6 + 试试。vue-easytable 要求 vue 2.6 以上版本
