### ISSUE TITLE
空数据的情况下，怎么显示暂无数据

### ISSUE THREAD

**Issue by ccljmcc** [Happy-Coding-Clans/vue-easytable#368]
空数据的情况下，怎么显示暂无数据

**Comment by ccljmcc** [comment]
我看了api，没有找到类似empty-text的对象

**Comment by huangshuwei** [comment]
是的，没有开放API ,可以自己实现，这样会更灵活一些。
我写了一个暂无数据示例你可以参考下：https://codesandbox.io/s/vue-easytable241-example-forked-dncqd

**Comment by huangshuwei** [comment]
官方文档添加了相应的示例：http://doc.huangsw.com/vue-easytable/#/zh/doc/table/data-empty
