### ISSUE TITLE
[Feature Request] May i know how to use this feature as a CDN method ?

### ISSUE THREAD

**Issue by haja-rr-dev** [Happy-Coding-Clans/vue-easytable#371]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
May i know how to use this feature as a CDN method ?

### 这个功能解决了什么问题？
I want to cdn links which is i add into header the use this feature

### 你期望的 API 是什么样的？
CDN links

**Comment by huangshuwei** [comment]
Please refer to http://doc.huangsw.com/vue-easytable/#/en/doc/start?anchor=usage-by-cdn

**Comment by haja-rr-dev** [comment]
Thank you 😊

 

From: Huang ShuWei ***@***.***>
Reply-To: Happy-Coding-Clans/vue-easytable ***@***.***>
Date: Sunday, 25 April 2021 at 12:45 PM
To: Happy-Coding-Clans/vue-easytable ***@***.***>
Cc: haja-rr-dev ***@***.***>, Author ***@***.***>
Subject: Re: [Happy-Coding-Clans/vue-easytable] [Feature Request] May i know how to use this feature as a CDN method ? (#371)

 

Please refer to http://doc.huangsw.com/vue-easytable/#/en/doc/start?anchor=usage-by-cdn
