### ISSUE TITLE
[Feature Request] Column Width Drag

### ISSUE THREAD

**Issue by muxiliu** [Happy-Coding-Clans/vue-easytable#372]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
请问大佬，在2.x的版本中去掉了列宽拖动的功能吗

### 这个功能解决了什么问题？
1.x版本中是有这个功能的，2.x去掉后，如果是一个多列的复杂合并的表头，每一个都需要设置列宽的话有点麻烦。

### 你期望的 API 是什么样的？
大佬在2.x中对这个拖动来设置列宽的方式有什么替代的方法吗/

**Comment by huangshuwei** [comment]
2.x 暂时不支持列宽拖动。

补充：相比较1.x ，2.x 单元格内容超出允许换行，列宽的拖动显得不那么重要

**Comment by chenbing11** [comment]
能通过自定义事件支持吗？

**Comment by hanshiyu1306410203** [comment]
大佬，问一下，2.5版本的表头合 去掉title-row了，如何设置表头的colspan和rowspan呢？

**Comment by imaxing** [comment]
> 2.x 暂时不支持列宽拖动。
> 
> 补充：相比较1.x ，2.x 单元格内容超出允许换行，列宽的拖动显得不那么重要。不过我也在尝试加上列宽拖动的功能

大佬, 近期有支持列拖拽的计划吗?  

来自可爱的甲方: 
![image](https://user-images.githubusercontent.com/26427785/147331952-7a5879f8-1aa1-4eeb-9856-699ab307f396.png)

**Comment by huangshuwei** [comment]
已经加到开发计划列表了：https://github.com/Happy-Coding-Clans/vue-easytable/projects/3#card-53939414

目前在做右键菜单功能，等这个功能开发上线，就会着手开发

**Comment by huangshuwei** [comment]
新版本已支持：
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.21.0
