### ISSUE TITLE
[Bug Report] 除了采用动态切换单元格class的方法外，能否通过动态地设置align的属性，设置特定位置的单元格的文本对齐

### ISSUE THREAD

**Issue by jiniechen** [Happy-Coding-Clans/vue-easytable#374]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
优化

### Issue 标题
除了采用动态切换单元格class的方法外，能否通过动态地设置align的属性，设置特定位置的单元格的文本对齐

### 仓库版本
2.5.1

### Vue 版本
2.6.12

### 浏览器
Chrome 

### 系统类型
Windows

### 重现链接
<a href="n/a" target="_blank">n/a</a>

### 重现步骤
cellStyleOption: {
          bodyCellClass: ({ row, column, rowIndex }) => {
            if (column.field === "hobby") {
              return "table-body-cell-class1";
            }

            if (column.field === "name" && rowIndex === 2) {
              return "table-body-cell-class2";
            }
          },
        }

### 期望的结果是什么？
cellStyleOption: {
          bodyCellClass: ({ row, column, rowIndex }) => {
            if (column.field === "hobby") {
              return {align:"right"};
            }

            if (column.field === "name" && rowIndex === 2) {
              return {align:"center"};
            }
          },
        }

### 实际的结果是什么？
建议扩展api

**Comment by huangshuwei** [comment]
1、如果想要动态改变某一列的单元格对齐方式，可以动态的设置列的对齐方式。参考示例：https://codesandbox.io/s/vue-easytable250-example-forked-qn5ro
2、如果你想要某一个单元格对齐方式单独设置，你也可以通过 `renderBodyCell`回调实现，使用方式参考：http://doc.huangsw.com/vue-easytable/#/zh/doc/table/cell-custom?anchor=body-zi-ding-yi-dan-yuan-ge
