### ISSUE TITLE
[Bug Report] default filter can not have a filterList dynamically

### ISSUE THREAD

**Issue by oliolivia** [Happy-Coding-Clans/vue-easytable#375]
`###` 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
default filter can not have a filterList dynamically

### 仓库版本
2.5.1

### Vue 版本
2.6.12

### 浏览器
firefox 89.0b3

### 系统类型
macOS Big Sur 11.3.1

### 重现链接
<a href="https://codesandbox.io/s/0jdo5" target="_blank">https://codesandbox.io/s/0jdo5</a>

### 重现步骤
- declare variable filterList: [] in data,
- pass this.filterList to filter.filterList
- give this.filterList a value in mounted or any other place

### 期望的结果是什么？
I want to get a filterList based on the table content, who would change when table content changes, for exemple:
```
let names = [...new Set(this.initData.map(x => x.name))]
for(i=0;i< names.length;i  ) {
   this. filterList.push({value: i, label: names[i], selected: false})
}
// this.columns[0].filter.filterList = filterList
```

so the declaration of columns would be like:

```
columns: [
          { 
                  field: "name", key: "a", title: "Name", align: "left", width: "15%", 
                  filter: {
                           filterList: this.filterList,
                           ...
                  }
         },
          ...
]
```

### 实际的结果是什么？
 The filterList has to be defined constantly in the code before everything ...  

### 补充说明（可选）
This shouldn't be a bug(or there is definitely a way to do so)
The sandbox is the same as that in the documentation, the "filter" icon doesn't show. I hope I explained this clearly. Looking forward to your response.

**Comment by huangshuwei** [comment]
Sorry to get back to you so late.

You can use `computed` to solve  the problem. here is the demo:
https://codesandbox.io/s/vue-easytable250-example-forked-s9726?file=/Example.vue

**Comment by oliolivia** [comment]
I've tried use computed to do this, here is the result, maybe I did it wrong ?
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/47084828/119116092-7d7b7d00-ba5a-11eb-8a37-42d0579352cc.png">

**Comment by oliolivia** [comment]
@huangshuwei   In my case, I tried to calculate a list using init table
```
computed: {
    filterList() {
        let dates = [...new Set(this.sourceData.map(x => x.date))]
        let result = []
        for(i=0;i<dates.length;i++) {
          this.result.push({value: i, label: dates[i], selected: false})
        }
        return this.result
    }
}
```

**Comment by huangshuwei** [comment]
you should put `column` in computed.
like this:
https://codesandbox.io/s/vue-easytable250-example-forked-9eg18?file=/Example.vue

**Comment by oliolivia** [comment]
Yes ! that's it ! this works, thanks very much !!!

**Comment by huangshuwei** [comment]
you are welcome
