### ISSUE TITLE
[Bug Report] fixed right with children

### ISSUE THREAD

**Issue by dlishtvan-onix-systems** [Happy-Coding-Clans/vue-easytable#376]
### I am opening an issue for
vue-easytable

### Issue Type
Bug

###  Issue Title
fixed right with children

### library Version
2.5.1

### Vue Type
2.6.12

### Browser Type
Chrome

### System version
mac

### Reproduction url
<a href="https://codesandbox.io/s/vue-easytable251-example-forked-nu6pk?file=/Example.vue" target="_blank">https://codesandbox.io/s/vue-easytable251-example-forked-nu6pk?file=/Example.vue</a>

### Step to reproduce
fixed right col with children

### What is expected?
correct right position

### What is actually happening?
wrong right position

### Any additional comments? (optional)
help me pls)

**Comment by huangshuwei** [comment]
The new version has solved this problem.

**Comment by dlishtvan-onix-systems** [comment]
@huangshuwei thanks a lot, you made great job!
