### ISSUE TITLE
[Feature Request] 安装后vue-easytable后，import VueEasytable from "vue-easytable"报错

### ISSUE THREAD

**Issue by yangzm0618** [Happy-Coding-Clans/vue-easytable#380]
### I am opening an issue for
vue-easytable

### Issue Type
Feature

###  Issue Title
安装后vue-easytable后，import VueEasytable from "vue-easytable"报错

### What problem does this feature solve?
 error  in ./node_modules/vue-easytable/libs/main.js  Module parse failed: Unexpected token (1:42333) You may need an appropriate loader to handle this file type. 找不出原因了，vue用2.0，npm 3.0

### What does the proposed API look like?
 error  in ./node_modules/vue-easytable/libs/main.js  Module parse failed: Unexpected token (1:42333) You may need an appropriate loader to handle this file type. 找不出原因了，vue用2.0

**Comment by huangshuwei** [comment]
#363

**Comment by huangshuwei** [comment]
麻烦提供一个可复现的仓库。目前我定位不到问题，谢谢

**Comment by huangshuwei** [comment]
The new version fixes this problem:
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/2.5.3
