### ISSUE TITLE
[Bug Report] 列设置百分比宽度时会随列数据长度的变化而变化

### ISSUE THREAD

**Issue by dongwenpeng** [Happy-Coding-Clans/vue-easytable#386]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
列设置百分比宽度时会随列数据长度的变化而变化

### 仓库版本
2.5.5

### Vue 版本
2.6.14

### 浏览器
Google

### 系统类型
Mac

### 重现链接
<a href="https://codesandbox.io/s/objective-mclaren-87g7b" target="_blank">https://codesandbox.io/s/objective-mclaren-87g7b</a>

### 重现步骤
1. 设置百分比宽度
2. 开启行省略
3. 单列数据存在比较长的字符

### 期望的结果是什么？
当设置百分比宽度时不会随着列数据过长而导致列长度超出百分比限制

### 实际的结果是什么？
当设置百分比宽度时会随着列数据过长而导致列长度超出百分比限制

### 补充说明（可选）
或许这并不是一个Bug，但我期望得到这样的结果，感谢。

**Comment by huangshuwei** [comment]
感谢反馈，我想这应该是一个新功能。可以通过添加这个样式满足你要的功能：https://developer.mozilla.org/zh-CN/docs/Web/CSS/word-break

这个功能晚点时间支持

**Comment by dongwenpeng** [comment]
> 感谢反馈，我想这应该是一个新功能。可以通过添加这个样式满足你要的功能：https://developer.mozilla.org/zh-CN/docs/Web/CSS/word-break
> 
> 这个功能晚点时间支持

首先，感谢您提供这样一个好用的组件，在 vue-easytable v1 版本就一直在使用，很高兴看到您继续开发 V2 版本。

**Comment by huangshuwei** [comment]
谢谢支持。
这功能我考虑了下，使用样式处理比组件开放API 的方式更合理。见示例：https://codesandbox.io/s/funny-dew-cuwgs?file=/src/App.vue

因为文本换行功能本身就是通过样式控制的，通过开放一个API 会显得多余。后面我会在文档里添加换行的示例。

**Comment by huangshuwei** [comment]
文档已更新，添加了 [长文本破坏布局](https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/column-width?anchor=chang-wen-ben-po-pi-bu-ju) 示例
