### ISSUE TITLE
[Feature Request] Row group

### ISSUE THREAD

**Issue by medibox** [Happy-Coding-Clans/vue-easytable#387]
### I am opening an issue for
vue-easytable

### Issue Type
Feature

###  Issue Title
Row group

### What problem does this feature solve?
I want feature row group or can config colspan for expand a row to full of table.

### What does the proposed API look like?
nothing

**Comment by huangshuwei** [comment]
What does the "Row group" look like? Please provide a reference link or a picture.

**Comment by medibox** [comment]
use cell span ok. 
Thank you.
