### ISSUE TITLE
[Bug Report] disable column (type = checkbox)

### ISSUE THREAD

**Issue by fkrhtmq123** [Happy-Coding-Clans/vue-easytable#388]
### I am opening an issue for
vue-easytable

### Issue Type
Bug

###  Issue Title
disable column (type = checkbox)

### library Version
2.5.5

### Vue Type
2.6.11

### Browser Type
Chrome/91.0.4472.164

### System version
Windows

### Reproduction url
<a href="https://codesandbox.io/s/fast-architecture-9wkr6?file=/src/components/HelloWorld.vue" target="_blank">https://codesandbox.io/s/fast-architecture-9wkr6?file=/src/components/HelloWorld.vue</a>

### Step to reproduce
loork codeSanbox

### What is expected?
So that you can see the checkbox in column.

### What is actually happening?
The type checkbox in column disappears.

**Comment by huangshuwei** [comment]
Enable the multi selection through the `checkboxOption` attribute：
https://codesandbox.io/s/lucid-wood-fui6s?file=/src/components/HelloWorld.vue

**Comment by fkrhtmq123** [comment]
If the value of table data is true, can't I check the checkbox?

**Comment by huangshuwei** [comment]
You can use `defaultSelectedRowKeys`  as the default selected rows. Example:
https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/row-checkbox?anchor=default-selected
