### ISSUE TITLE
[Bug Report] 为什么点击表格以外的地方会重现渲染一次表格，并且执行所有表格相关的函数

### ISSUE THREAD

**Issue by qaz505876013** [Happy-Coding-Clans/vue-easytable#389]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
为什么点击表格以外的地方会重现渲染一次表格，并且执行所有表格相关的函数

### 仓库版本
2.5.5

### Vue 版本
2.6.14

### 浏览器
 Chrome 92.0.4515.107

### 系统类型
Windows 10

### 重现链接
<a href="无" target="_blank">无</a>

### 重现步骤
为什么点击表格以外的地方会重现渲染一次表格，并且执行所有表格相关的函数

### 期望的结果是什么？
执行其他非表格能不能不要重新渲染表格

### 实际的结果是什么？
点击表格以外的地方会重现渲染一次表格

### 补充说明（可选）
在官方例子在写运行中也可以重现，在某个相关函数中打印，点击非表格区域，都会重新打印

**Comment by huangshuwei** [comment]
希望给个可以重新的示例，官方示例有这个bug 也可以贴出来。谢谢

**Comment by qaz505876013** [comment]
![image](https://user-images.githubusercontent.com/12541379/127467182-9637ce29-b94d-4a29-bb1b-138939600e25.png)
例如这个cell样式的例子，在bodyCellClass加一句打印，点击红框中的地方，每点击一次都会打印。我是前端小白，这个是本来设计就这样的么。

**Comment by huangshuwei** [comment]
新版本已修复：
