### ISSUE TITLE
[Feature Request] 选择器嵌套过于复杂，建议简化

### ISSUE THREAD

**Issue by Vinsea** [Happy-Coding-Clans/vue-easytable#395]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
选择器嵌套过于复杂，建议简化

### 这个功能解决了什么问题？
- 便于用户重写覆盖本组件的样式
- 加快`cssom tree`解析速度

### 你期望的是什么样的？
如[单元格样式](https://github.com/Happy-Coding-Clans/vue-easytable/blob/master/packages/style/ve-table.less#L264)，期望：
```css
.ve-table-body-td {
  color: #666;
}
```
现状：
```css
.ve-table table.ve-table-content tbody.ve-table-body tr.ve-table-body-tr td.ve-table-body-td, 
.ve-table table.ve-table-content tbody.ve-table-body tr.ve-table-expand-tr td.ve-table-body-td{
  ...
}
```
导致用户要么用权重更高的选择器，要么全部加 `!important`

### 其他
如果作者同意的话我可以一起参与修改，如果因为某些原因按兵不动的话就当我路过~

**Comment by huangshuwei** [comment]
> 便于用户重写覆盖本组件的样式

如果你想重写表格样式，建议使用 [主题定制方案](https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/theme)，默认的主题变量[在这里](https://github.com/Happy-Coding-Clans/vue-easytable/blob/master/packages/theme-default/var.less)


> 加快cssom tree解析速度

我宁愿牺牲这点解析速度，来降低维护成本

**Comment by Vinsea** [comment]
> > 便于用户重写覆盖本组件的样式
> 
> 如果你想重写表格样式，建议使用 [主题定制方案](https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/theme)，默认的主题变量[在这里](https://github.com/Happy-Coding-Clans/vue-easytable/blob/master/packages/theme-default/var.less)
> 
> > 加快cssom tree解析速度
> 
> 我宁愿牺牲这点解析速度，来降低维护成本

了解~
