### ISSUE TITLE
[Bug Report] Vue Easytable not working in ie11

### ISSUE THREAD

**Issue by s1ncho** [Happy-Coding-Clans/vue-easytable#396]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
Vue Easytable not working in ie11

### 仓库版本
2.7.0

### Vue 版本
2.6.14

### 浏览器
Internet Explorer 11

### 系统类型
Windows 10 x64

### 重现链接
<a href="https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/table-width" target="_blank">https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/table-width</a>

### 重现步骤
Open any example of official site in ie 11, is not working 

### 期望的结果是什么？
to make it work in ie11

### 实际的结果是什么？
is not working

**Comment by huangshuwei** [comment]
[New version supported](https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.8.0)
