### ISSUE TITLE
[Feature Request] 设置renderBodyCell的同时支持width自适应

### ISSUE THREAD

**Issue by sycamore1115** [Happy-Coding-Clans/vue-easytable#398]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
设置renderBodyCell的同时支持width自适应

### 这个功能解决了什么问题？
当设置了renderBodyCell自定义单元格渲染函数之后，必须要设置一个宽度，不能做到宽度自适应，这样就导致表格宽度不能随内容自适应。

### 你期望的 API 是什么样的？
希望设置了renderBodyCell的同时，如果不设置width，即为宽度自适应

**Comment by huangshuwei** [comment]
单元格宽度如果不设置，那么就会随着内容自适应。我更新了[这个示例](https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/cell-custom?anchor=body-zi-ding-yi-dan-yuan-ge)

具体列宽设置说明[参考文档](https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/column-width)
