### ISSUE TITLE
是否考虑支持左侧多级表头？

### ISSUE THREAD

**Issue by saonian** [Happy-Coding-Clans/vue-easytable#40]
是否考虑支持左侧多级表头？一些复杂的报表这块用的比较多。

**Comment by huangshuwei** [comment]
> 是否考虑支持左侧多级表头？一些复杂的报表这块用的比较多。

什么是‘左侧多级表头’，不妨细说😁

**Comment by saonian** [comment]
是我没说清楚，目前的多级表头针对的是列，放在顶部。我说的多级表头是针对的行，放在左侧。

**Comment by huangshuwei** [comment]
> 目前的多级表头针对的是列，放在顶部。我说的多级表头是针对的行，放在左侧。

那就是行单元格合并，这个满足吗
http://doc.huangsw.com/vue-easytable/app.html#/table?anchor=table-cell-merge

把左侧的单元格合并应该就是你要的了吧

**Comment by huangshuwei** [comment]
上个图吧，看着清楚

**Comment by saonian** [comment]
> 那就是行单元格合并，这个满足吗
http://doc.huangsw.com/vue-easytable/app.html#/table?anchor=table-cell-merge

单元格合并某种程度是可以解决问题，不过方式不够优雅，表头这样的结构性数据需要加入到表数据结构里面，且需要计算合并行数。

![image](https://user-images.githubusercontent.com/5100460/32590859-92edf2ae-c557-11e7-9524-6799fe8b8c0a.png)

**Comment by huangshuwei** [comment]
这种表格即使用原生html 写也是累的半死，无论用什么table组件写都不会方便多少。
除非开发出一个可视化的界面，编辑完成后，自动生成代码。
这是我的想法，如果有时间我尝试写一个可视化的table编辑功能...

**Comment by huangshuwei** [comment]
> 确实是的，找了很多组件几乎都没有支持到这块。如果页面表格能像EXCEL那样编辑生成就是最好了。

因为难度大😂

如果你找到类似功能table组件发出来参考下，我后面也准备写一个试试，不一定成功
