### ISSUE TITLE
[Feature Request] Row checkbox not correctly worket of the pagination

### ISSUE THREAD

**Issue by s1ncho** [Happy-Coding-Clans/vue-easytable#401]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
Row checkbox not correctly worket of the pagination

### 这个功能解决了什么问题？
When you click on the checkbox for selecting all lines, all lines on the current page are selected. On other pages, the lines remain unselected. How to select all records if multiple pages?

### 你期望的 API 是什么样的？
An example of how highlighting works with pagination like gmail.com. The ability to select all rows by page, remembering the already selected rows, or all records regardless of pages.

**Comment by huangshuwei** [comment]
> When you click on the checkbox for selecting all lines, all lines on the current page are selected. On other pages, the lines remain unselected. How to select all records if multiple pages?

You can use `selectedRowKeys`  to achieve this function. I'll write a demo later

**Comment by huangshuwei** [comment]
I added an example of pagination with row checkbox, [Refer to example](https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/pagination?anchor=with-row-checkbox). Logic of this example like [gmail](https://mail.google.com/)

**Comment by s1ncho** [comment]
Thanks. The issue is resolved
