### ISSUE TITLE
[Feature Request] Ability to override the reset function in the multiple filter

### ISSUE THREAD

**Issue by s1ncho** [Happy-Coding-Clans/vue-easytable#402]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
Ability to override the reset function in the multiple filter

### 这个功能解决了什么问题？
https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/header-filter?anchor=mixed-use
For example, when you click on reset, set values from the NAME_FILTER_LIST array (filterList). Now function reset the values are set
regardless of filterList.
You can also add "select all" with the first checkbox.

### 你期望的 API 是什么样的？
The reset function returns the state of the filter according to the array filterList

**Comment by huangshuwei** [comment]
You may be able to do this through [custom header filter](https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/header-filter-custom)
