### ISSUE TITLE
[Bug Report] 切换表格时，右侧固定列阴影不显示

### ISSUE THREAD

**Issue by ww0625** [Happy-Coding-Clans/vue-easytable#404]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
切换表格时，右侧固定列阴影不显示

### 仓库版本
2.7.0

### Vue 版本
2.6.14

### 浏览器
Chrome  93.0.4577.82

### 系统类型
Windows

### 重现链接
<a href="https://docs.qq.com/doc/DZWtiRU5kTFVKaXZU" target="_blank">https://docs.qq.com/doc/DZWtiRU5kTFVKaXZU</a>

### 重现步骤
1.进入第一个列表，列表右侧固定列阴影正常显示
2.不动滚动条，切换到另一个列表，此列表右侧固定列阴影不展示
3.  2.6.1版本的代码改了阴影的问题，此问题不存在，但2.7.0及之后的版本，加了判断，具体链接中已截图

### 期望的结果是什么？
切换列表，右侧固定列阴影正常展示

### 实际的结果是什么？
切换列表，右侧固定列阴影不展示

**Comment by huangshuwei** [comment]
> https://docs.qq.com/doc/DZWtiRU5kTFVKaXZU
这个链接我看不了

**Comment by ww0625** [comment]
![image](https://user-images.githubusercontent.com/42986901/135038707-365bae03-3fd9-430c-bf32-5fb59197a098.png)

**Comment by ww0625** [comment]
是否可以在 initVirtualScroll 方法里对 this.$options.customOption.previewTableContainerScrollLeft 的值进行重置

若有其他方式解决，请说明一下 感谢

**Comment by huangshuwei** [comment]
可以提供一个可以复现的示例吗，2个表格应该不会共享同一个 `previewTableContainerScrollLeft `变量才对

**Comment by zhangjiayu1215** [comment]
https://codesandbox.io/s/frosty-shape-7e2i8?file=/Example.vue

最开始以为是keep-alive或router-view导致的，但是不加也可以复现

**Comment by huangshuwei** [comment]
[已修复并发布](https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.8.3)
