### ISSUE TITLE
[Feature Request] 支持特殊表头合并

### ISSUE THREAD

**Issue by genos999** [Happy-Coding-Clans/vue-easytable#412]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
支持表头合并

### 这个功能解决了什么问题？
支持多个表头合并 下方单元格可独立显示数据

### 你期望的 API 是什么样的？
表头可合并

**Comment by hengwuming** [comment]
> ![微信截图_20211029170406](https://user-images.githubusercontent.com/44758946/139408049-59650ab1-e9ef-4017-b37c-09571a1af15c.png) 红框这一块合并成一个整体的表头 上下不用隔离开这种

我现在是直接操作dom来修改colSpan和rowSpan，来进行表头的合并 。
