### ISSUE TITLE
[Bug Report] Virtual scroll table with expand option that renders another table inside crashes browser tab

### ISSUE THREAD

**Issue by stephantabor** [Happy-Coding-Clans/vue-easytable#414]
### I am opening an issue for
vue-easytable

### Issue Type
Bug

###  Issue Title
Virtual scroll table with expand option that renders another table inside crashes browser tab

### library Version
2.9.0

### Vue Type
2.6.14

### Browser Type
Version 95.0.4638.69 (Official Build) (x86_64)

### System version
macOS 11.4

### Reproduction url
<a href="https://stackblitz.com/edit/vuejs-starter-r9x3jc?file=table.js" target="_blank">https://stackblitz.com/edit/vuejs-starter-r9x3jc?file=table.js</a>

### Step to reproduce
1. Open demo page directly by clicking "Open in new window" at the top right of the screen
2. Expand any row
3. The tab crashes

### What is expected?
The browser tab does not crash

### What is actually happening?
The browser tab crashes

![image](https://user-images.githubusercontent.com/8570366/140796655-06809f5b-eb27-47b7-94bf-dfef77dfc59d.png)

**Comment by huangshuwei** [comment]
Thanks for your report.

This is a bug. Strangely, when you expand a virtual table, everything is normal. Here is a demo:https://stackblitz.com/edit/vuejs-starter-wvzf6h?file=table2.js

So, I need to continue troubleshooting

**Comment by huangshuwei** [comment]
[The new version](https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.10.2) has fixed this bug.

This is the modified demo:https://stackblitz.com/edit/vuejs-starter-qsf7hx?file=package.json

And I added an expanded table example, Please refer to:https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/virtual-scroll?anchor=combination-row-expand-table
