### ISSUE TITLE
[Feature Request] 选中回调的参数增加是否需要选中行的完整数据

### ISSUE THREAD

**Issue by imaxing** [Happy-Coding-Clans/vue-easytable#416]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
选中回调的参数增加是否需要选中行的完整数据

### 这个功能解决了什么问题？
表格选中场景并非都是获取选中行的主key提交到后台, 有的时候行编辑需要提交完整的数据到后台, 还需要根据key循环获取主数据

### 你期望的 API 是什么样的？
checkbox-option: { 
     // 比如 给了fullData为true, 回调可以拿到selectedRows, 而不是selectedRowKeys
     fullData: true,
     selectedAllChange({ selectedRows }) {
       // 可以获取到选中的所有数据
      // ajax.post('xxx', { data: selectedRows })
     }
 }

**Comment by huangshuwei** [comment]
这样会让API 很冗余，因为 rowKey 就是唯一值，选中的行数据可以通过 rowKey 获取。

有个场景，表格数据上千条，全选后回调参数数据量将会非常大

**Comment by imaxing** [comment]
> 这样会让API 很冗余，因为 rowKey 就是唯一值，选中的行数据可以通过 rowKey 获取。
> 
> 有个场景，表格数据上千条，全选后回调参数数据量将会非常大

了解! 那如果返回对应的index呢?

**Comment by huangshuwei** [comment]
这里之所以没有返回 index，因为index 有些场景并不是唯一的，比如分页或者结合虚拟滚动，index 都不是你想要的的，而 `rowKey`是唯一的

**Comment by imaxing** [comment]
> 这样会让API 很冗余，因为 rowKey 就是唯一值，选中的行数据可以通过 rowKey 获取。
> 
> 有个场景，表格数据上千条，全选后回调参数数据量将会非常大

大佬, 了解了! 我自己把row_key换成index就可以了, 虽然index变化会导致table重新渲染😂

**Comment by imaxing** [comment]
> 这里之所以没有返回 index，因为index 有些场景并不是唯一的，比如分页或者结合虚拟滚动，index 都不是你想要的的，而 `rowKey`是唯一的
