### ISSUE TITLE
Adding border-radius

### ISSUE THREAD

**Issue by roma177** [Happy-Coding-Clans/vue-easytable#418]
I have a simple table inside template tag, which I want to have a border-radius. How can I do that, seems that adding css to all table default classess does not affect it.

>   <div class="session-results">
    <ve-table
      id="loading-container"
      :columns="columns"
      :table-data="tableData"
    />
  </div>

**Comment by huangshuwei** [comment]
Thanks for your report. It's really inconvenient to add border radius at present. I'll fix this in the next version.

Now you can solve it in the following way:
```javascript
<ve-table
  style="border-radius: 10px; border: 1px solid #eee; overflow: hidden"
  :border-around="false"
  id="loading-container"
  :columns="columns"
  :table-data="tableData"
/>
```

**Comment by huangshuwei** [comment]
The new version makes it easier to set the border-radius: https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/border?anchor=border-radius
