### ISSUE TITLE
Sorting values rendered by renderBodyCell

### ISSUE THREAD

**Issue by roma177** [Happy-Coding-Clans/vue-easytable#419]
Is there a way to sort index column rendered by 

>   renderBodyCell: ({ row, column, rowIndex }, h) => {
>             return ++rowIndex;
>           },

What would `sortChange(params) ` function look like?
It seems that available examples do not work in that case as there is no values inside `field` and `tableData` objects.

**Comment by huangshuwei** [comment]
You are right. The custom index will be reset after sorting. You can sort the data in the table.
