### ISSUE TITLE
双击编辑输入框如何自定义？

### ISSUE THREAD

**Issue by striver-lyc** [Happy-Coding-Clans/vue-easytable#426]
你好，双击编辑输入框如何自定义？例如双击编辑切换成文本域输入框

**Comment by huangshuwei** [comment]
单元格编辑功能这段时间在重构，目标是按照excel 功能去做，新功能支持编辑的文本换行。预计最迟明天发布，你可以试用下

**Comment by huangshuwei** [comment]
新版本已发布，单元格编辑进行了重构，欢迎体验：
https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/cell-edit?anchor=kuai-jie-jian
