### ISSUE TITLE
老大，设置表头背景色不生效啊，其它功能都正常

### ISSUE THREAD

**Issue by zhouhm** [Happy-Coding-Clans/vue-easytable#427]
vue-easytable 2.11和2.12两个版本我都试了，都不行啊
参考您的文档https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/cell-style
原封不动的拷贝下来，不生效
拷贝的代码片段如下：
`<ve-table ...省略  :cell-style-option="cellStyleOption" />
`
`<script>
    export default {
        data() {
            return {
                cellStyleOption: {
                    headerCellClass: ({ column, rowIndex }) => {
                        if (rowIndex === 0) {
                            return "table-header-cell-class";
                        }
                    },
                },
...省略`

`<style>
    .table-header-cell-class {
        background: #91d5ff !important;
        color: #fff !important;
    }
</style>`

研究两天了，快疯了^_^ ^_^

**Comment by huangshuwei** [comment]
可能你的表头样式被其他地方样式覆盖了。运行在sandcodebox 是可以单独设置头部单元格背景的：https://codesandbox.io/s/vue-easytable-2-12-0-example-forked-l01yj?file=/Example.vue:228-243

另外，如果你只是想给表头设置统一的背景色，可以使用主题定制：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/theme

**Comment by zhouhm** [comment]
我就是二把刀啊，连拷贝带懵的，快把代码写完了，前端用的vue，后端用的Python3+flask
没用那么多模块啊，会冲突？

**Comment by zhouhm** [comment]
$ npm list
test1@0.1.0 /home/zhouhm/vuedemo/test1
├── @vue/cli-plugin-router@4.5.13
├── @vue/cli-plugin-vuex@4.5.13
├── @vue/cli-service@4.5.13
├── axios@0.21.1
├── bindings@1.5.0 extraneous
├── bootstrap-vue@2.21.2
├── bootstrap@4.6.0
├── dayjs@1.10.7
├── file-uri-to-path@1.0.0 extraneous
├── moment-timezone@0.5.34
├── moment@2.29.1
├── nan@2.15.0 extraneous
├── vue-easytable@2.12.0
├── vue-monthly-picker@0.2.8
├── vue-router@3.5.2
├── vue-template-compiler@2.6.14
├── vue@2.6.14
└── vuex@3.6.2

**Comment by huangshuwei** [comment]
有一点你要注意 `<style>` 标签不可以使用`scoped`属性

**Comment by zhouhm** [comment]
老大你真是我的偶像啊！把<style>的scoped去掉成功了
今晚喝酒庆祝！没搞清楚原理
我都想直接改你的源代码重新编译了
cd node_modules
git clone -b v2.12.0 --depth=1 https://github.com/Happy-Coding-Clans/vue-easytable.git
cd vue-easytable
然后直接修改packages/theme-default/var.less
最后再
npm install
npm run build
这方法太笨了太笨了
