### ISSUE TITLE
[Bug Report] 虚拟滚动结合行展开表格展开时空白 

### ISSUE THREAD

**Issue by huangzhiyong123456** [Happy-Coding-Clans/vue-easytable#429]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
虚拟滚动结合行展开表格展开时空白 

### 仓库版本
2.12.1

### Vue 版本
2.6.14

### 浏览器
Chrome  96.0.4664.110

### 系统类型
mac

### 重现链接
<a href="https://codesandbox.io/s/cmf0m?file=/Example.vue" target="_blank">https://codesandbox.io/s/cmf0m?file=/Example.vue</a>

### 重现步骤
在虚拟滚动结合行展开表格 的样例中展开第一行。出现空白

### 期望的结果是什么？
展开时正常渲染

### 实际的结果是什么？
展开时空白渲染

**Comment by huangshuwei** [comment]
我这无法重现，请再核对下提供的重现信息，谢谢

![重现](https://user-images.githubusercontent.com/6047141/146899870-a0b311a8-479b-4405-b3e7-81fe6d84bdb2.gif)

**Comment by huangshuwei** [comment]
不过我是 windows 系统，有可能是系统原因，我排查下

**Comment by huangshuwei** [comment]
mac 系统也已经测试过，没有重现你反馈的问题

**Comment by huangzhiyong123456** [comment]
https://user-images.githubusercontent.com/69354677/147020018-39140e2a-9b9d-4bbd-9b5b-428464965707.mp4

我是在官网上看的，现在滚动上面，下面变空白了。https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/virtual-scroll

**Comment by huangzhiyong123456** [comment]
https://user-images.githubusercontent.com/69354677/147023051-526f50df-0550-4508-b245-d7c654b9e90c.mp4

**Comment by huangshuwei** [comment]
感谢反馈，问题已重现。目前定位到是多个table组件实例复用变量导致，单个table 组件开启虚拟滚动不会有问题。后续版本修复

**Comment by huangshuwei** [comment]
新版本bug已修复：https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.12.3
