### ISSUE TITLE
Change default text

### ISSUE THREAD

**Issue by roma177** [Happy-Coding-Clans/vue-easytable#432]
Is there a way to change default text 'next 5 pages' and 'previous 5 pages' at pagination arrows hover for other text? Or maybe to disable showing text completely if cannot change?

**Comment by huangshuwei** [comment]
Of course. You can change the default text by `VeLocale.update()` function. [Refer to doc](https://happy-coding-clans.github.io/vue-easytable/#/en/doc/locale?anchor=override-default-configs)

By the way, Why do you want to change the default text，Is the text description not accurate enough?

**Comment by roma177** [comment]
Thank you, it worked, just needed to change default language for another.
