### ISSUE TITLE
[Feature Request] 编辑时进行增加数据验证。

### ISSUE THREAD

**Issue by America-first-melon** [Happy-Coding-Clans/vue-easytable#434]
### I am opening an issue for
vue-easytable

### Issue Type
Feature

###  Issue Title
编辑时进行增加数据验证。

### What problem does this feature solve?
编辑数据时，可以传入校验函数，校验不通过可以红框提示或者error提示。

**Comment by huangshuwei** [comment]
感谢反馈，我已经将这个新功能加入了待开发列表：https://github.com/Happy-Coding-Clans/vue-easytable/projects/3#card-75210590

**Comment by huangshuwei** [comment]
可以通过 `beforeCellValueChange` 和 `afterCellValueChange`进行编辑验证。文档：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/cell-edit?anchor=api
