### ISSUE TITLE
[Bug Report] 虚拟滚动   input  不能删除输入的value值

### ISSUE THREAD

**Issue by eightweb** [Happy-Coding-Clans/vue-easytable#440]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
虚拟滚动   input  不能删除输入的value值

### 仓库版本
2.13.0

### Vue 版本
2.6.14

### 浏览器
chrome

### 系统类型
windows

### 重现链接
<a href="无" target="_blank">无</a>

### 重现步骤
虚拟滚动列表, 结合自定义单元格, input输入框 只能输入, 不能删除

### 期望的结果是什么？
可输入, 可删除

### 实际的结果是什么？
不可删除value值

**Comment by huangshuwei** [comment]
收到，我排查下

**Comment by huangshuwei** [comment]
我这边排查了下，开启虚拟滚动后是可以编辑以及删除的，复现案例：
https://codesandbox.io/s/vue-easytable-2-13-0-example-forked-oltuh?file=/Example.vue

效果：
![test](https://user-images.githubusercontent.com/6047141/150783706-15db5d80-391f-488d-8973-2f00c83caad7.gif)

**Comment by huangshuwei** [comment]
今天刚修复了一个bug，当column 的 key 没有和 field 一致时，单元格无法修改。此bug 已修复：https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.13.1
