### ISSUE TITLE
[Feature Request] 增加边框时是否能进行边框拖动

### ISSUE THREAD

**Issue by vipcsgs** [Happy-Coding-Clans/vue-easytable#446]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
增加边框时是否能进行边框拖动

### 这个功能解决了什么问题？
使用过程了解到-vue-easytable-已基本满足大部分需求,但数据本身并非长度一致,部分较长部分较短,目前采取省略号加浮动显示,但使用人员表示应当能拖动边框调整展示宽度,但发现并不具备此功能

### 你期望的 API 是什么样的？
希望能和elementUi一样具备边框拖动改变列宽

**Comment by huangshuwei** [comment]
感谢你的反馈，已经在开发了。
开发计划：https://github.com/Happy-Coding-Clans/vue-easytable/projects/3#card-53939414

重复 #340
