### ISSUE TITLE
在弹出框中有复杂表头的列表无法正常显示

### ISSUE THREAD

**Issue by ricpi** [Happy-Coding-Clans/vue-easytable#45]
在弹出的对话框中，带有复杂表头的列表设置了isHorizontalResize,style="width:100%",columns的width，isResize，对话框弹出后表格不显示，拖动网页宽度后，列表正常显示
![issue](https://user-images.githubusercontent.com/5546157/32939860-df5a76a2-cbbb-11e7-8e56-26934bb8c7e9.png)
@huangshuwei

**Comment by huangshuwei** [comment]
是否未弹出对话框时，table 组件就已经实例化了，如果是这样，你试试在弹出对话框后，执行 table 的 `resize()`方法。
实例参考：
http://doc.huangsw.com/vue-easytable/app.html#/table?anchor=table-hide-table-resize

如果不行再反馈

**Comment by ricpi** [comment]
@huangshuwei 问题已解决，十分感谢

**Comment by huangshuwei** [comment]
不客气

**Comment by ricpi** [comment]
执行 table 的 resize()方法 在有些浏览器上不能解决问题，例如QQ浏览器、Opera浏览器，mac os 系统上，这个要怎么处理呢

**Comment by huangshuwei** [comment]
好的，我测下兼容性

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
