### ISSUE TITLE
ios15以上系统 ，当有合并表头，滚动时表头会错位

### ISSUE THREAD

**Issue by zqmhub** [Happy-Coding-Clans/vue-easytable#451]

**Comment by 13043547498** [comment]
ios机型上,合并的表头top=45px效果变成top=0，

**Comment by huangshuwei** [comment]
感谢反馈，我需要花点时间定位这个问题

**Comment by 13043547498** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Happy-Coding-Clans/vue-easytable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月2日(星期三) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Happy-Coding-Clans/vue-easytable] ios15以上系统 ，当有合并表头，滚动时表头会错位 (Issue #451)





 
感谢反馈，我需要花点时间定位这个问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huangshuwei** [comment]
> ios机型上,合并的表头top=45px效果变成top=0，

什么浏览器，以及版本多少，我这边需要重现问题

**Comment by 13043547498** [comment]
我们的还页面是内嵌到app中的，至于电脑上的浏览器都是可以的，只有ios手机上的浏览器会出现，目前会出现问题的手机，都是iphone 11,12

**Comment by 13043547498** [comment]
后面试了一下，13也不行，版本是15.4.1

**Comment by huangshuwei** [comment]
这个组件库不推荐在移动端使用，有些功能会有兼容问题。我们计划下半年会单独开源移动端的组件库

**Comment by sea-caterpillar** [comment]
> 这个组件库不推荐在移动端使用，有些功能会有兼容问题。我们计划下半年会单独开源移动端的组件库

你好，单独开源移动端组件库在进行了吗，预计什么时候可以发布使用？

**Comment by huangshuwei** [comment]
感谢你的关注，预计2022年底发布
