### ISSUE TITLE
[Bug Report] Virtual scrolling with expanding rows causes the problem that  infinite jitter of the table

### ISSUE THREAD

**Issue by huangshuwei** [Happy-Coding-Clans/vue-easytable#453]
### I am opening an issue for
vue-easytable

### Issue Type
Bug

###  Issue Title
Virtual scrolling with expanding rows causes the problem that  infinite jitter of the table

### library Version
v2.14.0

### Vue Type
2.6.11

### Browser Type
Chorme 98.0.4758.102

### System version
Windows

### Reproduction url
<a href="https://codesandbox.io/s/vue-easytable-2-14-0-example-forked-hdy5n6?file=/Example.vue" target="_blank">https://codesandbox.io/s/vue-easytable-2-14-0-example-forked-hdy5n6?file=/Example.vue</a>

### Step to reproduce
1、Scroll to the bottom

### What is expected?
normal scroll

### What is actually happening?
It will lead to infinite jitter of the table

**Comment by ankitsinghaniyaz** [comment]
@huangshuwei any solution to this? I'm not using expanded row but I'm still facing this.

**Comment by huangshuwei** [comment]
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.21.7
