### ISSUE TITLE
[Bug Report] keep-alive缓存样式问题

### ISSUE THREAD

**Issue by keter0202** [Happy-Coding-Clans/vue-easytable#454]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
keep-alive缓存样式问题

### 仓库版本
v2.14.0

### Vue 版本
Vue2.6.11

### 浏览器
Chrome 87.0.4280.141

### 系统类型
Windows

### 重现链接
<a href="无" target="_blank">无</a>

### 重现步骤
table配置了fixed: 'left'，排序图标的样式就缓存不了

### 期望的结果是什么？
能正常缓存

### 实际的结果是什么？
不能正常缓存

**Comment by huangshuwei** [comment]
官方的文档路由配置的是 keep-alive ，你可以先点击排序图标，再点击其他菜单，然后再回到原来的页面：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/header-sort

如果你还无法定位到问题，可以提供一个可复现的例子，我帮你定位下

**Comment by keter0202** [comment]
> 官方的文档路由配置的是 keep-alive ，你可以先点击排序图标，再点击其他菜单，然后再回到原来的页面：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/header-sort
> 
> 如果你还无法定位到问题，可以提供一个可复现的例子，我帮你定位下

复现

**Comment by keter0202** [comment]
> 

复现的链接地址：https://codesandbox.io/s/vue-easytable-2-14-1-example-forked-fccpti?file=/Example.vue

**Comment by huangshuwei** [comment]
非常感谢你的反馈，问题重现了，修复后我会在这里通知

**Comment by huangshuwei** [comment]
bug 已修复：https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.14.2

**Comment by keter0202** [comment]
好的，谢谢大佬 @huangshuwei 

> bug 已修复：https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.14.3
