### ISSUE TITLE
[Bug Report] 虚拟滚动 合并行，上下滚动后列会错位

### ISSUE THREAD

**Issue by Ryoma007** [Happy-Coding-Clans/vue-easytable#458]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
虚拟滚动 合并行，上下滚动后列会错位

### 仓库版本
v2.14.4

### Vue 版本
2.6.11

### 浏览器
Chrome 98.0.4758.102

### 系统类型
Windows

### 重现链接
<a href="https://codesandbox.io/s/xu-ni-gun-dong-he-bing-xing-6b6dti?file=/Example.vue" target="_blank">https://codesandbox.io/s/xu-ni-gun-dong-he-bing-xing-6b6dti?file=/Example.vue</a>

### 重现步骤
等表格初始化完毕后，上下滚动

### 期望的结果是什么？
在上下滚动的过程中合并行也要正确显示效果。例如合并10行，当第1行滚出可视区域，剩余2-9行也是合并的效果

### 实际的结果是什么？
当首行（rowspan返回大于0）不在界面上时，其余行（rowspan返回0）也都不显示，右侧的列会往左移一位

**Comment by huangshuwei** [comment]
[新版本](https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.15.0) bug 已修复

你可以通过使用新增的属性 `bufferCount`解决这个问题，具体示例：https://codesandbox.io/s/vue-easytable-2-15-0-example-forked-59v7b4?file=/Example.vue
