### ISSUE TITLE
[Feature Request] 建议增大fixed列的z-index值

### ISSUE THREAD

**Issue by Yusoo** [Happy-Coding-Clans/vue-easytable#463]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
建议增加fixed列的z-index值

### 这个功能解决了什么问题？
目前fixed=left的列，z-index值是 1。
如果右边有使用自定义单元格的、比较复杂的组件，有些本身也会使用z-index，这样当向右横向滚动的时候，自定义单元格的内容会显示在fixed列的上层

### 你期望的 API 是什么样的？
默认的z-index值设置在100以上，为自定义组件留一点操作空间

**Comment by Yusoo** [comment]
目前发现在自定义组件的最外层加上z-index: 0，可以解决这个问题

**Comment by huangshuwei** [comment]
感谢你的反馈，大致明白你说的意思，可否给到一个可复现的例子，我需要设计下这个功能。谢谢

**Comment by Yusoo** [comment]
大概像这个例子，建议像element那样可以自己配置初始 z-index，不影响旧项目
https://codesandbox.io/s/63bcyw?file=/Example.vue

**Comment by huangshuwei** [comment]
新版本已支持：https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.21.3

补充：如果需要自定义 z-index ,你可以通过主题定制的方式使用
