### ISSUE TITLE
[Feature Request] 拖动排序功能

### ISSUE THREAD

**Issue by txlife** [Happy-Coding-Clans/vue-easytable#468]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
拖动排序功能

### 这个功能解决了什么问题？
在账单项目列表中，可以通过拖拽对行进行排序

### 你期望的 API 是什么样的？
是否可以将SortableJS融入此组件中

**Comment by huangshuwei** [comment]
谢谢你的反馈，已经在计划中了。 重复 #420
