### ISSUE TITLE
[Feature Request] Cell Edit support function

### ISSUE THREAD

**Issue by tonokim** [Happy-Coding-Clans/vue-easytable#469]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
Cell Edit support function

### 这个功能解决了什么问题？
有些情况需要根据数据来判断 cell是否可以编辑

### 你期望的 API 是什么样的？
edit: ({ row, column }) => {
    return false
},

* 返回 true可以编辑，返回false不可编辑

**Comment by huangshuwei** [comment]
v2.18.0 版本已支持：https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.18.0
