### ISSUE TITLE
[Bug Report] 编辑时 编辑框位置异常

### ISSUE THREAD

**Issue by hnzzmsf** [Happy-Coding-Clans/vue-easytable#471]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
编辑时 编辑框位置异常

### 仓库版本
v2.16.1

### Vue 版本
vue2

### 浏览器
chrome 99.0.4844.74

### 系统类型
mac

### 重现链接
<a href="暂无" target="_blank">暂无</a>

### 重现步骤
大概50个列, 列是动态配置的

### 期望的结果是什么？
可以正常编辑

### 实际的结果是什么？
编辑框位置异常

![https://cdn.youdi.net/F/1/3/7/f/a/71c3c23af91ce6ee163a0313090.png](https://cdn.youdi.net/F/1/3/7/f/a/71c3c23af91ce6ee163a0313090.png)

**Comment by huangshuwei** [comment]
帮忙提供一个可复现的例子吧，我自己没有重现，谢谢。模板：https://codesandbox.io/s/vue-easytable-template-yg2iu

**Comment by huangshuwei** [comment]
bug 已修复：https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.17.2
