### ISSUE TITLE
如何实现表格数据双向绑定？

### ISSUE THREAD

**Issue by davidwang1207** [Happy-Coding-Clans/vue-easytable#473]
你好， 很棒的表格！
我刚学玩端不久， 觉得这个功能很强大，感谢贡献出来。
我初始化了数据，数据之间有联动，页面改了一个数据之后 后续的数据会自动调整。 如果有双向绑定那就太好了，可惜我不知道如何才能做到。

**Comment by davidwang1207** [comment]
行数据是拼出来，不是正好的数据。

**Comment by huangshuwei** [comment]
抱歉那么晚才回复你，不知道你说的双向绑定是不是表格数据变更表格的展示也跟着变的问题。如果是这个问题，那么表格是支持的
