### ISSUE TITLE
[Feature Request]右键单元格区域选择功能

### ISSUE THREAD

**Issue by mei2015** [Happy-Coding-Clans/vue-easytable#474]
希望能加入右键拖动选择 eletron 等应用 需要这个功能

**Comment by huangshuwei** [comment]
> 希望能加入右键拖动选择 eletron 等应用 需要这个功能

这个功能没太明白，可以较详细的描述下吗？谢谢

**Comment by mei2015** [comment]
![image](https://user-images.githubusercontent.com/10136065/164610842-9fc803d4-f695-4387-b994-ed40f60d5893.png)
ag-grid 那种 你的这个已经很强了 在差几个功能就 nb了  1、拖拽 分类栏排序 
![image](https://user-images.githubusercontent.com/10136065/164611058-ae821ff9-dbb6-481e-bb42-5e9cd8d84926.png)
![image](https://user-images.githubusercontent.com/10136065/164611096-91d0810b-c960-4ce7-b5c6-ce18b7c7b706.png)

**Comment by mei2015** [comment]
aggrid 要收费  只能自己破解后使用，国产的还没有 发现 只有你这个 相近 单不完全是

**Comment by huangshuwei** [comment]
上面的截图包含的功能太多了，列拖动、拖动分组。希望可以具化一个功能需求

**Comment by mei2015** [comment]
> 上面的截图包含的功能太多了，列拖动、拖动分组。希望可以具化一个功能需求

拖动选中右键功能

**Comment by mei2015** [comment]
三个功能加上完美了！
1、区域选中右键功能
2、标题header拖拽位置功能
3、表头格式化筛选功能

**Comment by huangshuwei** [comment]
目前已支持区域选择右键功能。
1、更新日志：https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.19.0
2、体验示例：https://happy-coding-clans.github.io/vue-easytable/#/zh/demo
