### ISSUE TITLE
[Feature Request] 表头和内容行的align可否分开设置？

### ISSUE THREAD

**Issue by Hanoso** [Happy-Coding-Clans/vue-easytable#475]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
表头和内容行的align可否分开设置？

### 这个功能解决了什么问题？
表头和行的align必须同步问题。

### 你期望的 API 是什么样的？
长内容时，我希望行内align='left'，但是表头仍然需要align='center'，而不是两者同步。

**Comment by huangshuwei** [comment]
可以通过单元格内容自定义功能，实现表头和内容单元格单独对齐设置：

**Comment by huangshuwei** [comment]
目前从产品设计的角度，为什么会出现表头的对齐与内容对齐不一致的情况，希望可以描述下。如果是特殊的需求，就按照上面的方式就行
