### ISSUE TITLE
[Bug Report] 关于edit编辑的功能

### ISSUE THREAD

**Issue by vbird-coder** [Happy-Coding-Clans/vue-easytable#482]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
关于edit编辑的功能

### 仓库版本
v2.17.2

### Vue 版本
2.6.10

### 浏览器
chrome

### 系统类型
windows

### 重现链接
<a href="https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/cell-edit" target="_blank">https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/cell-edit</a>

### 重现步骤
在使用编辑功能的时候，edit:ture 的行数据，只有一开始在data定义完成的数据才可以编辑，在后面通过created发送请求后得到的tabledata数据便不能进行编辑的功能。请问我要怎么做。

### 期望的结果是什么？
后面请求的tabledata数据也可以进行编辑

### 实际的结果是什么？
不能编辑。

**Comment by huangshuwei** [comment]
没有重现你说的问题。重现示例：https://codesandbox.io/s/vue-easytable-2-17-2-example-forked-42bq1r?file=/Example.vue

**Comment by vbird-coder** [comment]
> 没有重现你说的问题。重现示例：https://codesandbox.io/s/vue-easytable-2-17-2-example-forked-42bq1r?file=/Example.vue

我刚刚又详细的测试下，我发现tabledata定义之后push进去的数据无法编辑

**Comment by vbird-coder** [comment]
> 没有重现你说的问题。重现示例：https://codesandbox.io/s/vue-easytable-2-17-2-example-forked-42bq1r?file=/Example.vue

不好意思，我又尝试了一下，这真是个神奇的bug，也许可能是我的设备问题，我在copy成功的数据字段能编辑，我自己手敲一模一样却不行。现在问题以解决，感谢感谢。
