### ISSUE TITLE
[Feature Request]  列头支持拖动。以及列头宽度支持手动调整

### ISSUE THREAD

**Issue by Arthaskj** [Happy-Coding-Clans/vue-easytable#488]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
 列头支持拖动。以及列头宽度支持手动调整

### 这个功能解决了什么问题？
方便用户自定义自己的列头显示

### 你期望的 API 是什么样的？
类似于antd pro

**Comment by vbird-coder** [comment]
＋ 1

**Comment by Arthaskj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jiujiubanban** [comment]
同问 有计划支持拖拽么？🌟

**Comment by vbird-coder** [comment]
> ＋ 1

到现在还没有啥动静，，，要换表格组件了。。。痛苦。。

**Comment by huangshuwei** [comment]
新版本已支持：
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.21.0
