### ISSUE TITLE
[Bug Report] Occur error when use Cell Custom to create button

### ISSUE THREAD

**Issue by DavyGGit** [Happy-Coding-Clans/vue-easytable#492]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
Occur error when use Cell Custom to create button

### 仓库版本
v2.17.3

### Vue 版本
v2.6.14

### 浏览器
Chrome 98.0.4758.102

### 系统类型
Windows10

### 重现链接
<a href="https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/cell-custom" target="_blank">https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/cell-custom</a>

### 重现步骤
I've used following sample code 

renderBodyCell: ({ row, column, rowIndex }, h) => {
                            return (
                                <span class="text-bold" style="color:#1890ff;">
                                    {  rowIndex}
                                </span>
                            );
                        },
and browser responded error message:
Uncaught SyntaxError: Unexpected token '<'

Both API description and Vue.js Official doc I've already search, but it didn't render normally. 
Is there any other way to try?

### 期望的结果是什么？
Buttons can work in cells of a table

### 实际的结果是什么？
Buttons didn't show and get some error messages

**Comment by huangshuwei** [comment]
You need use jsx . Refer to vue doc:https://v2.vuejs.org/v2/guide/render-function.html#ad
