### ISSUE TITLE
[Bug Report] 如何自定义滚动条样式？

### ISSUE THREAD

**Issue by leigu-bol** [Happy-Coding-Clans/vue-easytable#493]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
如何自定义滚动条样式？

### 仓库版本
v2.17.3

### Vue 版本
 vue2.6.14

### 浏览器
Chrome 87.0.4280.141

### 系统类型
Windows

### 重现链接
<a href="https://jsfiddle.net/huangsw/nqe3qogv/" target="_blank">https://jsfiddle.net/huangsw/nqe3qogv/</a>

### 重现步骤
参考历史的issue都没有解决

### 期望的结果是什么？
滚动条匹配黑色主题

### 实际的结果是什么？
滚动条是白色的

**Comment by huangshuwei** [comment]
组件内部并没有重写滚动条样式，所以直接作用到滚动条的元素即可。
如何重写滚动条样式根据你的业务场景而定，参考：https://developer.mozilla.org/zh-CN/docs/Web/CSS/::-webkit-scrollbar
