### ISSUE TITLE
[Feature Request] hide of the table header

### ISSUE THREAD

**Issue by rahimramezanian** [Happy-Coding-Clans/vue-easytable#495]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
remove header row

### 这个功能解决了什么问题？
I would like to remove the header row. I used 
```
cellStyleOption: {
        headerCellClass: ({ column, rowIndex }) => {
          return "table-header-noheader";
        },
      },
.table-header-noheader {
  display: none !important;
}
```
but still there is a space above table for header. The above code only hide `<th>` but it should act on `<thead><tr>`.

### 你期望的 API 是什么样的？
:showheader="false"

**Comment by huangshuwei** [comment]
Thanks for your report. This feature will be supported in the next release.

At present, you can handle it through this way:

In your vue file:
```
<div class='table-container'>
    <ve-table />
</div>
```

In your style file:
```
.table-container{
   .ve-table-header{ 
        display: none;
  }
}
```

**Comment by huangshuwei** [comment]
The new version is supported:
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.18.0
