### ISSUE TITLE
[Bug Report] resizeobserver loop limit exceeded

### ISSUE THREAD

**Issue by ckmzlf** [Happy-Coding-Clans/vue-easytable#501]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
resizeobserver loop limit exceeded

### 仓库版本
v2.18.0

### Vue 版本
vue2.6

### 浏览器
chrome80，chrome103

### 系统类型
windows

### 重现步骤
使用window.onerror监听，必现提示resizeobserver loop limit exceeded，跟element-ui的table提示有点类似

### 期望的结果是什么？
不再提示resizeobserver loop limit exceeded

### 实际的结果是什么？
提示resizeobserver loop limit exceeded

**Comment by huangshuwei** [comment]
此错误意味着 ResizeObserver 无法在单个动画帧内传递所有观察结果。它是良性的（您的网站不会崩溃）。如果需要屏蔽这个报告可以通过以下方式：
```
const e = window.onerror;
window.onerror = function (message, source, lineno, colno, error) {
    if (message === "ResizeObserver loop limit exceeded") {
        console.warn("Ignored: ResizeObserver loop limit exceeded");
        return false;
    } else {
        return e(...arguments);
    }
};
```

**Comment by Shaohong-Alex-Feng** [comment]
通过window.addEventListener进行的监控，修改onerror并不好用

**Comment by lennokiki** [comment]
webpack编译时报的错，改一下vue.config.js配置，改完之后需要重启

`
  devServer: {
    client: {
      overlay: false
    },
  }
`
