### ISSUE TITLE
[Feature Request] 可以手动控制选择区域，现在没有找到当用户选择区域后，有没有事件 知道用户选中了区域位置的方法

### ISSUE THREAD

**Issue by FengShaduVIP** [Happy-Coding-Clans/vue-easytable#502]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
可以手动控制选择区域，现在没有找到当用户选择区域后，有没有事件 知道用户选中了区域位置的方法

### 这个功能解决了什么问题？
可以手动控制选择区域，现在没有找到当用户选择区域后，有没有事件 知道用户选中了区域位置的方法

### 你期望的 API 是什么样的？
可以手动控制选择区域，现在没有找到当用户选择区域后，有没有事件 知道用户选中了区域位置的方法

**Comment by huangshuwei** [comment]
感谢你的反馈，下一个版本支持

**Comment by huangshuwei** [comment]
新版本已实现：
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.20.0

**Comment by ydwan** [comment]
> 新版本已实现： https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.20.0

能新增一个onSelectionChange事件吗？选中了哪些单元格
