### ISSUE TITLE
[Feature Request] 拖拽行，进行row 的数据排序

### ISSUE THREAD

**Issue by xyhxmzg** [Happy-Coding-Clans/vue-easytable#503]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
拖拽行，进行row 的数据排序

### 这个功能解决了什么问题？
拖拽行，进行row 的数据排序

### 你期望的 API 是什么样的？
拖拽行，进行row 的数据排序

**Comment by huangshuwei** [comment]
感谢你的反馈，重复 issue #420
