### ISSUE TITLE
[Feature Request] Intercept header filter popper dropdown close event

### ISSUE THREAD

**Issue by arcadeJHS** [Happy-Coding-Clans/vue-easytable#504]
### I am opening an issue for
vue-easytable

### Issue Type
Feature

###  Issue Title
Intercept header filter popper dropdown close event

### What problem does this feature solve?
Is it possible to intercept the "on close" event of the popper dropdown opened by header filters? I mean: to intercept it when I click outside it with the mouse. Currently the dropdown closes, and I cannot intercept this event to, for instance, clear the selected filter value.

### What does the proposed API look like?
I would need a hook to intercept this event in order to trigger a callback.

**Comment by huangshuwei** [comment]
New version has been implemented：
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.20.0
