### ISSUE TITLE
Error on callback method beforeVisibleChange({nextVisible}) #504

### ISSUE THREAD

**Issue by arcadeJHS** [Happy-Coding-Clans/vue-easytable#505]
New version has been implemented：
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.20.0

_Originally posted by @huangshuwei in https://github.com/Happy-Coding-Clans/vue-easytable/issues/504#issuecomment-1250245322_

I thank you for fast implementing my request!
But... I guess there is an error in the code, which prevent the right execution of the "closeFn" in a "filterCustom" definition.
When you call "closeFn", even though your return "true" from the "beforeVisibleChangeCallback" the dropdown never closes.

Could it be caused by a wrong execution of the code inside "beforeVisibleChangeCallback" method in "ve-dropdown/rc/index.jsx" file? 

Maybe you should invert the check "if (isFunction(beforeVisibleChange))", executing it as the first statement:

```
        // before visible change callback
        beforeVisibleChangeCallback(nextVisible) {
            // console.log("nextVisible22::", nextVisible);
            const { beforeVisibleChange, isDropdownVisible } = this;

            if (isFunction(beforeVisibleChange)) {
                // next visible
                return beforeVisibleChange({
                    nextVisible,
                });
            }

            if (nextVisible === isDropdownVisible) {
                return false;
            }
        },
```

**Comment by huangshuwei** [comment]
Thanks for your report. This bug has been fixed : https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.20.1

**Comment by arcadeJHS** [comment]
Thanx!
