### ISSUE TITLE
单元格编辑 。下拉select的怎么实现，现在好像只有input编辑

### ISSUE THREAD

**Issue by in68** [Happy-Coding-Clans/vue-easytable#51]
单元格编辑 。下拉select的怎么实现，现在好像只有input编辑

**Comment by huangshuwei** [comment]
现在还不支持编辑状态下包含 select

**Comment by jianliulin** [comment]
希望添加下拉带分页的grid，同时可以过滤。用途:选择产品等信息比较多数量比较多的基础数据

**Comment by jianliulin** [comment]
下拉的select希望能支持远程url获取数据

**Comment by 544751779** [comment]
@huangshuwei  希望添加 需求较多

**Comment by robin1885** [comment]
费了老大劲把select整到了table里，但是用不了，洗洗脸，还是滚回动态表单了。
