### ISSUE TITLE
[Feature Request] vue3版本有计划开发吗

### ISSUE THREAD

**Issue by tzwhyqq** [Happy-Coding-Clans/vue-easytable#512]
### 选择要提交 issue 的库
vue-easytable
2.20.2
### Issue 类型
Feature

### Issue 标题
vue3版本有计划开发吗

### 这个功能解决了什么问题？
现在我们项目上都是vue3.0，3.0 版本有在计划中吗

### 你期望的 API 是什么样的？
适应 vue3.0  使用。

**Comment by huangshuwei** [comment]
vue3 请参考这里 #508
