### ISSUE TITLE
可以直接在 html 中使用吗？

### ISSUE THREAD

**Issue by iceshou** [Happy-Coding-Clans/vue-easytable#516]
我们有一个老项目，还是和 jsp 混用的，所以要单独导入的形式，这个可以直接在 html 中的形式使用吗？

**Comment by huangshuwei** [comment]
可以的，通过 CDN 方式使用：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/start?anchor=cdn-fang-shi-shi-yong
