### ISSUE TITLE
[Feature Request] 请问下有没有表格单元格输入的字段校验功能？

### ISSUE THREAD

**Issue by Jeson123** [Happy-Coding-Clans/vue-easytable#517]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
请问下有没有表格单元格输入的字段校验功能？

### 这个功能解决了什么问题？
在进行表格单元格输入时校验表格字段是否符合输入的表格字段的类型，如只能输入数字或字母还有输入内容的长度等

### 你期望的 API 是什么样的？
可以设置表格单元格内容的输入长度和输入类型，还有校验显示效果和相应的提示文字显示

**Comment by huangshuwei** [comment]
可以的，参考示例：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/cell-edit?anchor=ji-ben-yong-fa

**Comment by Jeson123** [comment]
thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Happy-Coding-Clans/vue-easytable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 中午11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Happy-Coding-Clans/vue-easytable] [Feature Request] 请问下有没有表格单元格输入的字段校验功能？ (Issue #517)





 
可以的，参考示例：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/cell-edit?anchor=ji-ben-yong-fa

**Comment by Jeson123** [comment]
thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Happy-Coding-Clans/vue-easytable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 中午11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Happy-Coding-Clans/vue-easytable] [Feature Request] 请问下有没有表格单元格输入的字段校验功能？ (Issue #517)





 
Closed #517 as completed.
