### ISSUE TITLE
单元格会自动加上line-height:40px ?

### ISSUE THREAD

**Issue by yseasony** [Happy-Coding-Clans/vue-easytable#52]
![image](https://user-images.githubusercontent.com/2038344/33198756-e31d0f72-d127-11e7-85ca-4e8cee06692d.png)

**Comment by huangshuwei** [comment]
是的，这是表体行高的默认值，可以通过属性`row-height`设置

**Comment by yseasony** [comment]
设置了:row-height="40px" 或者 row-height="40px" 表格都不能够正常显示

**Comment by huangshuwei** [comment]
> 设置了:row-height="40px" 或者 row-height="40px" 表格都不能够正常显示

这样，和设置表格高度一样
:row-height="40"

**Comment by yseasony** [comment]
发现 height: 40px; line-height: 40px; 会同时修改，其实我想把line-height: 40px 去掉。。

**Comment by huangshuwei** [comment]
去掉就不能上下居中了，你是想换行？
如果列可能不够宽可以给表格的`columns`对象设置`overflowTitle`属性，当列宽不够时鼠标悬浮会有‘title’效果

**Comment by yseasony** [comment]
我想自由些，一些样式自己来控制。这些样式写在了dom style上。。。

**Comment by huangshuwei** [comment]
恩，目前不行

**Comment by yseasony** [comment]
加油

**Comment by huangshuwei** [comment]
😂

**Comment by jekip** [comment]
请问，单元格如何让他显示2行，并且超出显示省略号、

**Comment by enng0227** [comment]
请问，单元格如何让他显示2行，并且超出显示省略号、

**Comment by sknightq** [comment]
@huangshuwei 
请问下表格头部高度有参数可以设置么，我看row-height只对表格body部分有效
