### ISSUE TITLE
[Bug Report] 速速升级  Upgrade to vue3

### ISSUE THREAD

**Issue by suifeng156** [Happy-Coding-Clans/vue-easytable#520]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
速速升级  Upgrade to vue3

### 仓库版本
v2.21.6

### Vue 版本
3

### 浏览器
Chrome

### 系统类型
 Windows

### 重现链接
<a href="www.baidu.com" target="_blank">www.baidu.com</a>

### 重现步骤
快速速升级

### 期望的结果是什么？
快速速升级

### 实际的结果是什么？
快速速升级

### 补充说明（可选）
速速升级

**Comment by huangshuwei** [comment]
感谢你的关注。重复 #508
