### ISSUE TITLE
[Feature Request] vue3已经发布了，请问有计划出个vue3版本的吗？我在vue3的项目里使用easytable直接报错

### ISSUE THREAD

**Issue by frh10** [Happy-Coding-Clans/vue-easytable#527]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
vue3已经发布了，请问有计划出个vue3版本的吗？我在vue3的项目里使用easytable直接报错

### 这个功能解决了什么问题？
支持vue3

### 你期望的 API 是什么样的？
支持vue3

**Comment by huangshuwei** [comment]
感谢关注，已经计划开发了 #508
