### ISSUE TITLE
[Bug Report] 自定义单元格编辑时 单元格输入框内容只能输入无法删除

### ISSUE THREAD

**Issue by qinhualian** [Happy-Coding-Clans/vue-easytable#533]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
自定义单元格编辑时 单元格输入框内容只能输入无法删除

### 仓库版本
v2.21.9

### Vue 版本
vue2

### 浏览器
Chrome 

### 系统类型
Windows

### 重现链接
<a href="https://codesandbox.io/s/vue-easytable-2-13-0-example-forked-ghnfr8?file=/Example.vue" target="_blank">https://codesandbox.io/s/vue-easytable-2-13-0-example-forked-ghnfr8?file=/Example.vue</a>

### 重现步骤
单元格可选择 cellSelectionOption.enable=true
tableData数据中含有rowKey字段
（我尝试去掉rowKey 输入框就没有这个问题了）

### 期望的结果是什么？
输入框使用正常

### 实际的结果是什么？
输入框只能输入内容 不能使用backspace删除 也不能输入空格 

### 补充说明（可选）
您好 不知道这个链接是否能正常显示  我是根据#440 的示例您评论区的示例https://codesandbox.io/s/vue-easytable-2-13-0-example-forked-oltuh?file=/Example.vue修改了一点
 只修改了address字段的renderBodyCell方法  
   renderBodyCell: ({ row, column, rowIndex }) => {
            const text = row[column.field];
            return (
              <input
                type="text"
                style="width:100%"
                value={row[column.field]}
                on-blur={(e) => {
                  row[column.field] = e.target.value;
                }}
              ></input>
            );
          }

**Comment by qinhualian** [comment]
https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/cell-edit 
单元格编辑结合 element-ui的示例中  InputNumber 计数器的输入框也是只能输入内容或者替换  但是无法回退删除

**Comment by huangshuwei** [comment]
重复 #536
