### ISSUE TITLE
row-height和title-row-height无作用

### ISSUE THREAD

**Issue by codentropy** [Happy-Coding-Clans/vue-easytable#537]
<ve-table
      style="row-height: '10px', title-row-height: '15px'"
      title-row-height="15px"
      :row-height=10
      :columns="columns"
      :table-data="tableData"
    />
这样用row-height和title-row-height，行高都不起作用。可否提供一个例子？我的main.js如下，还需要别的信息吗
import Vue from 'vue'
import VueEasytable from 'vue-easytable' // import library
import 'vue-easytable/libs/theme-default/index.css' // import style
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
import App from './App'
import router from './router'

Vue.use(VueEasytable)
Vue.use(ElementUI)
Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  components: { App },
  template: '<App/>',
  render: (h) => h(App)
})

**Comment by codentropy** [comment]
另外请教，配置了可变列寬
      :scroll-width="0"
      :column-width-resize-option="{ enable: true }"
，改寬度时，本来向窄调整，但实际变宽了。这个不跟鼠标的现象是配置不多吗？

**Comment by huangshuwei** [comment]
> ```
> <ve-table
>   style="row-height: '10px', title-row-height: '15px'"
>   title-row-height="15px"
>   :row-height=10
>   :columns="columns"
>   :table-data="tableData"
> />
> ```
> 
> 这样用row-height和title-row-height，行高都不起作用。可否提供一个例子？我的main.js如下，还需要别的信息吗 import Vue from 'vue' import VueEasytable from 'vue-easytable' // import library import 'vue-easytable/libs/theme-default/index.css' // import style import ElementUI from 'element-ui' import 'element-ui/lib/theme-chalk/index.css' import App from './App' import router from './router'
> 
> Vue.use(VueEasytable) Vue.use(ElementUI) Vue.config.productionTip = false
> 
> /* eslint-disable no-new */ new Vue({ el: '#app', router, components: { App }, template: '', render: (h) => h(App) })

- 行高设置需要通过主题定制的方式设置，文档：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/theme?anchor=zhu-ti-ding-zhi
   - 用这2个变量实现你要的效果 @ve-table-head-row-height  @ve-table-body-row-height

**Comment by huangshuwei** [comment]
> 另外请教，配置了可变列寬 :scroll-width="0" :column-width-resize-option="{ enable: true }" ，改寬度时，本来向窄调整，但实际变宽了。这个不跟鼠标的现象是配置不对吗？

单独提一个 issue。谢谢
