### ISSUE TITLE
[Bug Report] 在选中多列隐藏这些列时，剩下未被隐藏的列的表头不在了 （ve-table-header-tr下的dom不存在）

### ISSUE THREAD

**Issue by qinhualian** [Happy-Coding-Clans/vue-easytable#538]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
在选中多列隐藏这些列时，剩下未被隐藏的列的表头不在了 （ve-table-header-tr下的dom不存在）

### 仓库版本
v2.21.9

### Vue 版本
vue2

### 浏览器
Chrome 

### 系统类型
Windows

### 重现链接
<a href="无" target="_blank">无</a>

### 重现步骤
选中多列，点击按钮隐藏选中的列，隐藏成功，但是剩下的列的表头没有了，表头的位置是一行空的。（选中单列再点击隐藏没有这个情况是正常显示的）
ps:与文档隐藏列的示例中不同的是我开启了区域选择功能
![Snipaste_2023-01-13_11-13-14](https://user-images.githubusercontent.com/73522318/212232033-aab38ac1-8696-4fc2-b355-c5c28ba0c035.png)
![image](https://user-images.githubusercontent.com/73522318/212232092-6f3ed63d-1ee4-418a-9007-2ba7b94d6d6c.png)
![image](https://user-images.githubusercontent.com/73522318/212232144-0c7f1c87-6558-4bac-b61c-baeabe8ff5d7.png)

### 期望的结果是什么？
正常显示表头

### 实际的结果是什么？
表头样式有问题

**Comment by huangshuwei** [comment]
已修复，请安装最新版本
