### ISSUE TITLE
[Feature Request] Disable Column resize in specific columns

### ISSUE THREAD

**Issue by micheldpcarlos** [Happy-Coding-Clans/vue-easytable#539]
### I am opening an issue for
vue-easytable

### Issue Type
Feature

###  Issue Title
Disable Column resize in specific columns

### What problem does this feature solve?
For now, it is possible to enable resizing columns, but it affects every column in the table. It is not possible to determine which ones you want to ignore, eg.: the checkbox column.

### What does the proposed API look like?
Under column options, add a "disableResize" property, false by default. 
So we can disable it.

**Comment by huangshuwei** [comment]
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.22.0
