### ISSUE TITLE
[Bug Report] vue3无法使用

### ISSUE THREAD

**Issue by zasray** [Happy-Coding-Clans/vue-easytable#540]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
vue3无法使用

### 仓库版本
v2.21.11

### Vue 版本
3.0

### 浏览器
safari

### 系统类型
ios

### 重现链接
<a href="*" target="_blank">*</a>

### 重现步骤
vue3无法使用

### 期望的结果是什么？
请尽快升级到vu3

### 实际的结果是什么？
暂时无法使用，已关注1年有余。

### 补充说明（可选）
我愿意为此付费或者捐献。

**Comment by tzwhyqq** [comment]
同求

**Comment by huangshuwei** [comment]
duplicate of #508
