### ISSUE TITLE
[Feature Request] Add vertical scrolling class to permit custom styling

### ISSUE THREAD

**Issue by looeyf** [Happy-Coding-Clans/vue-easytable#543]
### I am opening an issue for
vue-easytable

### Issue Type
Feature

###  Issue Title
Add vertical scrolling class to permit custom styling

### What problem does this feature solve?
When using the fixed header and no borders, it isn't possible to create a solution with just CSS (for example, a box-shadow) to separate the header from the table body.

### What does the proposed API look like?
When scrolling vertically, add a class to container's element as the horizontal scroll already has. Therefore, it'll be possible to reach any element inside the table and modify its styles with custom classes.

**Comment by huangshuwei** [comment]
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.23.0
