### ISSUE TITLE
[Bug Report] 单元格编辑问题Error in v-on handler: "TypeError: this.$refs.tableRef.startEditingCell is not a function"

### ISSUE THREAD

**Issue by cyb1999** [Happy-Coding-Clans/vue-easytable#548]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
Error in v-on handler: "TypeError: this.$refs.tableRef.startEditingCell is not a function"

### 仓库版本
v2.24.0

### Vue 版本
vue2.6

### 浏览器
Chrome 

### 系统类型
mac

### 重现链接
<a href="无" target="_blank">无</a>

### 重现步骤
https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/cell-edit
我完全按照这个文档走了一遍，
ve-table也绑定了ref="tableRef"
在button中：
`<button class="button-demo" @click="startEditingCell(0, 'example')">
      编辑单元格0-0
    </button>`
在methods中，也写了点击事件函数，
`startEditingCell(rowKey, colKey, defaultValue) {
      this.$refs['tableRef'].startEditingCell({ rowKey, colKey, defaultValue });
    },`
然后显示了这个报错

> 『Error in v-on handler: "TypeError: this.$refs.tableRef.startEditingCell is not a function"』

### 期望的结果是什么？
解决我的单元格编辑问题

### 实际的结果是什么？
无法使用单元格编辑功能

**Comment by cyb1999** [comment]
另外要说的是，我这个表格是放在表单中的，我的表单阻止了默认事件，难道和这个有关吗？

**Comment by crunch249** [comment]
已解决，升级了一下vue-easytable版本就好了

**Comment by cyb1999** [comment]
已解决，升级了一下vue-easytable的版本就好了
