### ISSUE TITLE
[Feature Request] 什么时候出vue3版本的

### ISSUE THREAD

**Issue by cousnecs** [Happy-Coding-Clans/vue-easytable#550]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
什么时候出vue3版本的

### 这个功能解决了什么问题？
可以使用vite安装调试

### 你期望的 API 是什么样的？
vue3 vite 似乎更简单

**Comment by huangshuwei** [comment]
感谢你的关注。重复 https://github.com/Happy-Coding-Clans/vue-easytable/discussions/508
