### ISSUE TITLE
[Bug Report] 浏览器 报   ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by tiantianchuangduixiang** [Happy-Coding-Clans/vue-easytable#552]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
浏览器 报   ResizeObserver loop limit exceeded

### 仓库版本
v2.24.0

### Vue 版本
2.7.14

### 浏览器
谷歌 111.0.5563.147

### 系统类型
Windows

### 重现链接
<a href="https://codesandbox.io/s/admiring-mountain-d4nxss?file=/webpack.config.js" target="_blank">https://codesandbox.io/s/admiring-mountain-d4nxss?file=/webpack.config.js</a>

### 重现步骤
使用vue-cli 不会报错  但是用webpack4 编译浏览器会报 超出循环次数   ResizeObserver loop limit exceeded

### 期望的结果是什么？
期望解决这个问题

### 实际的结果是什么？
实际就是不能在webpack上编译使用

**Comment by huangshuwei** [comment]
refer to https://github.com/Happy-Coding-Clans/vue-easytable/issues/501

**Comment by tiantianchuangduixiang** [comment]
我参考了 但是没有解决掉 还是在 弹出
