### ISSUE TITLE
[Bug Report] 参考了 51的回答 但是没有解决 浏览器报 ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by tiantianchuangduixiang** [Happy-Coding-Clans/vue-easytable#554]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
参考了 51的回答 但是没有解决 浏览器报 ResizeObserver loop limit exceeded

### 仓库版本
v2.24.0

### Vue 版本
2.7.14

### 浏览器
Chrome 111.0.5563.147

### 系统类型
Windows

### 重现链接
<a href="https://codesandbox.io/s/admiring-mountain-d4nxss?file=/Example.vue" target="_blank">https://codesandbox.io/s/admiring-mountain-d4nxss?file=/Example.vue</a>

### 重现步骤
使用webpack 编译 在开发环境 浏览器一直弹出ResizeObserver loop limit exceeded

### 期望的结果是什么？
该怎么解决这个问题  因为我在上次提出后  给了一个参考内容  但是那个参考内容不足以解决我的问题

### 实际的结果是什么？
无法阻止弹出  ResizeObserver loop limit exceeded

### 补充说明（可选）
参考 #51 内容后无发解决

**Comment by tiantianchuangduixiang** [comment]
是参考的   https://github.com/Happy-Coding-Clans/vue-easytable/issues/501  这个

**Comment by tiantianchuangduixiang** [comment]
> 我这正常，是否有其他信息你没提供到 ![image](https://user-images.githubusercontent.com/6047141/228407862-71c9147e-c4c1-4129-99c0-f7d46b938c00.png)

https://codesandbox.io/p/sandbox/cocky-mcclintock-byz8x8?file=%2Fmain.js&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A14%7D%5D

  这个是用webpack-dev-serve 启动的 可以复现

**Comment by huangshuwei** [comment]
这个属于webpack-dev-server 的bug： https://github.com/webpack/webpack-dev-server/issues/4771 ，你按照这个issue 试试

**Comment by tiantianchuangduixiang** [comment]
![1680072763141](https://user-images.githubusercontent.com/81840293/228451365-a740e6c5-9bfb-44c4-8df9-57775dda5a72.jpg)
这样解决了

**Comment by CaiWenlie** [comment]
> ![1680072763141](https://user-images.githubusercontent.com/81840293/228451365-a740e6c5-9bfb-44c4-8df9-57775dda5a72.jpg) 这样解决了

这犯规了吧，哪有改node_modules的...
