### ISSUE TITLE
[Bug Report] ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by Shaohong-Alex-Feng** [Happy-Coding-Clans/vue-easytable#563]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
ResizeObserver loop limit exceeded

### 仓库版本
v2.16.3

### Vue 版本
2.6.11

### 浏览器
chrome

### 系统类型
mac

### 重现链接
<a href="null" target="_blank">null</a>

### 重现步骤
加载table，报ResizeObserver loop limit exceeded

### 期望的结果是什么？
不要报错ResizeObserver loop limit exceeded

### 实际的结果是什么？
报ResizeObserver loop limit exceeded

**Comment by huangshuwei** [comment]
参考这个问题 #501
