### ISSUE TITLE
rowStyleOption里面的stripe 斑马线颜色是否可以支持自定义呢？

### ISSUE THREAD

**Issue by justdoitgo** [Happy-Coding-Clans/vue-easytable#564]
rowStyleOption里面的stripe 斑马线颜色是否可以支持自定义呢？

**Comment by huangshuwei** [comment]
可以通过主题定制实现，文档：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/theme
使用这个主题变量 https://github.com/Happy-Coding-Clans/vue-easytable/blob/master/packages/theme-default/var.less#L34

**Comment by justdoitgo** [comment]
感谢大佬~
