### ISSUE TITLE
[Bug Report] Still can delete cell with Delete key from Keyboard in cell that read only

### ISSUE THREAD

**Issue by hindarwan** [Happy-Coding-Clans/vue-easytable#573]
### I am opening an issue for
vue-easytable

### Issue Type
Bug

###  Issue Title
Still can delete with Delete key from Keyboard in cell that readonly

### library Version
v2.27.0

### Vue Type
2

### Browser Type
Edge 112.0.1722.48

### System version
Windows 11

### Reproduction url
<a href="https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/cell-edit?anchor=basic-usage" target="_blank">https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/cell-edit?anchor=basic-usage</a>

### Step to reproduce
1. Go to this documentation page: https://happy-coding-clans.github.io/vue-easytable/#/en/doc/table/cell-edit?anchor=basic-usage
2. Click on column 'Name' row number '1' that contain text 'You can't edit'.
3. Press Delete key from Keyboard

### What is expected?
Text in that cell not deleted.

### What is actually happening?
Text in that cell deleted.

**Comment by Majiale-tu** [comment]
不可以edit的单元格 可以被ctrl+v 复制内容填充，只读单元格是否可以去除其他外在操作！

**Comment by huangshuwei** [comment]
Sorry, this is a conflict between the editing function and the clipboard function. You can temporarily solve this problem through the `beforePaste`, `beforeCut`, and `beforeDelete `functions of the `clipboardOption`. Refer to api:https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/clipboard?anchor=api

**Comment by hindarwan** [comment]
> You can temporarily solve this problem through the `beforePaste`, `beforeCut`, and `beforeDelete `functions of the `clipboardOption`. Refer to api:https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/clipboard?anchor=api

Nice, it solve this problem. Thanks
