### ISSUE TITLE
粘贴值改变无法监听，导致无法设置验证

### ISSUE THREAD

**Issue by y16678889** [Happy-Coding-Clans/vue-easytable#575]
粘贴值改变无法监听，导致无法设置验证。使用粘贴功能无法触发edit中的事件

**Comment by huangshuwei** [comment]
你可以利用粘贴事件`afterPaste`去处理，参考文档：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/clipboard?anchor=api
