### ISSUE TITLE
[Bug Report] 如何解决虚拟滚动滚动条卡顿问题 有没有好的解决方案

### ISSUE THREAD

**Issue by miaofukai** [Happy-Coding-Clans/vue-easytable#587]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
如何解决虚拟滚动滚动条卡顿问题 有没有好的解决方案

### 仓库版本
v2.27.1

### Vue 版本
2.0

### 浏览器
Chrome

### 系统类型
Windows

### 重现链接
<a href="http://huangshuwei.gitee.io/vue-easytable/#/zh/doc/table/virtual-scroll" target="_blank">http://huangshuwei.gitee.io/vue-easytable/#/zh/doc/table/virtual-scroll</a>

### 重现步骤
表格中嵌套了element-ui中的输入框等组件 滚动时滚动条卡顿

### 期望的结果是什么？
滚动流畅就可以

### 实际的结果是什么？
滚动条卡顿

**Comment by huangshuwei** [comment]
麻烦给个可以复现的示例
