### ISSUE TITLE
[Bug Report] 使用element select组件时单元格复制不能动态绑定，只能复制单元格的value，组件监听不到变化

### ISSUE THREAD

**Issue by fangdayts** [Happy-Coding-Clans/vue-easytable#589]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Bug

### Issue 标题
使用element select组件时单元格复制不能动态绑定，只能复制单元格的value，组件监听不到变化

### 仓库版本
v2.27.1

### Vue 版本
2

### 浏览器
Chrome 

### 系统类型
Windows

### 重现链接
<a href="https://huangshuwei.gitee.io/vue-easytable/#/zh/doc/table/cell-edit" target="_blank">https://huangshuwei.gitee.io/vue-easytable/#/zh/doc/table/cell-edit</a>

### 重现步骤
编辑单元格，使用ctrl c复制任意select 组件的内容只出现value值 lable选项不出现，使用使用单元格自动填充向上或者向下拖动没有问题

### 期望的结果是什么？
有很多场景需要复制前面很多行相同的数据，希望能实现复制的时候label也能跟随变化

### 实际的结果是什么？
有很多场景需要复制前面很多行相同的数据，希望能实现复制的时候label也能跟随变化

**Comment by huangshuwei** [comment]
复制的确只能复制value值，因为label 值是通过 value转换的。如果你需要对复制、粘贴后的动作进行二次加工，可以通过剪贴板事件进行处理：https://happy-coding-clans.github.io/vue-easytable/#/zh/doc/table/clipboard?anchor=api
