### ISSUE TITLE
[Feature Request] 希望能增加点击表格外面不清除选中的配置

### ISSUE THREAD

**Issue by tanxuxu** [Happy-Coding-Clans/vue-easytable#591]
### 选择要提交 issue 的库
vue-easytable

### Issue 类型
Feature

### Issue 标题
希望能增加点击表格外面不清除选中的配置

### 这个功能解决了什么问题？
我试图在表格上面加一行工具栏，选中单元格时进行一些操作，结果发现只要我点击表格外面，表格选中状态就消失，getRangeCellSelection()也显示undefined

### 你期望的 API 是什么样的？
通过一个table的配置项

**Comment by huangshuwei** [comment]
重复 #570
