### ISSUE TITLE
能否点击表头的title也能排序？而不是非要点击icon三角才能排序？

### ISSUE THREAD

**Issue by SherryZhaoHui** [Happy-Coding-Clans/vue-easytable#68]

**Comment by huangshuwei** [comment]
最初是这样设计的，但是后面考虑到加表头数据过滤功能（有数据过滤小图标），后来去掉了。
如果你们的需求必须这么做，可以通过设置表头点击的回调函数处理`title-click`，在回调中处理你的逻辑

**Comment by huangshuwei** [comment]
是否已解决？

**Comment by SherryZhaoHui** [comment]
没有，回调中可以处理逻辑，但是样式方面存在一些问题

**Comment by zxrliuyan** [comment]
点击排序图标，无论点击上箭头还是下箭头，都是只有升序asc排序

**Comment by huangshuwei** [comment]
@zxrliuyan 
我这边看了没问题啊
https://jsfiddle.net/api/post/library/pure/

**Comment by zxrliuyan** [comment]
我更新新版本试试

**Comment by huangwenlong528** [comment]
排序的时候官方文档上写的是在sortChange（params）{}里面重新请求一下数据就行了，但是我直接重新请求数据是不起作用的，想请大神帮忙讲解一下。排序到底该怎么写呢？
