### ISSUE TITLE
[QUESTION] Vertical column drag

### ISSUE THREAD

**Issue by psolom** [Happy-Coding-Clans/vue-easytable#75]
Hey, thanks for great component!

You claimed a "Vertical column drag" feature in todo list.
Is this about dragging columns with mouse to change their order in the table?
If so I would love this feature. When do you plan implement it?

**Comment by huangshuwei** [comment]
thanks for support, "Vertical column drag" will change the order of columns.
But this feature will be added later.

**Comment by servocoder** [comment]
Awesome! Leave a note in this ticket once it is ready, please.

**Comment by huangshuwei** [comment]
no problem

**Comment by oliverbj** [comment]
Sorry to revive this topic - but was this ever implemented? :)
