### ISSUE TITLE
如果能支持列拖动就爽了 就可以满足我的所有需求了

### ISSUE THREAD

**Issue by CodeMonkeyXu** [Happy-Coding-Clans/vue-easytable#8]

**Comment by huangshuwei** [comment]
能否详细的描述下，纵向的列拖动还是横向的？

**Comment by CodeMonkeyXu** [comment]
纵向的整列拖动改变其位置

**Comment by huangshuwei** [comment]
这个有点难度，因为如果表头存在单元格合并，那么纵向的整列拖动就会有很大的局限性。不过应该也可以做到，这个我后面构思下

**Comment by CodeMonkeyXu** [comment]
表头不存在单元格合并的情况

**Comment by huangshuwei** [comment]
恩恩，明白你意思

**Comment by CodeMonkeyXu** [comment]
还有一个小需求 行内编辑能实现点击一行 那么这一行所有可编辑的单元格都处于可编辑状态 但是每个单元格可能不一样,有文本框 数字框 日期选择 下拉框这些 
这个能做到吗? 感觉写起来好复杂

**Comment by huangshuwei** [comment]
大兄弟，这的确有难度。你重新开一个 issue , 这是一个新需求。
感谢你的建议，只要有需求的，我都尽量实现

**Comment by killdada** [comment]
同求，，如果可以把这个拖动列独立成api的话更好。

**Comment by huangshuwei** [comment]
@killdada 
目前的想法是：
传入 `drag-column-done`回调函数，整列拖动结束后，把拖动完成后的列的信息传入`drag-column-done`回调函数

**Comment by guowangsheng** [comment]
同求 普通表格列支持拖动
