### ISSUE TITLE
使用列宽移动时,高度足够的情况下出现纵向滚动条,控制台显示错误

### ISSUE THREAD

**Issue by 328921371** [Happy-Coding-Clans/vue-easytable#83]
如图
![1](https://user-images.githubusercontent.com/30221150/34754861-70974474-f5fb-11e7-8aae-a5763ec113b2.png)
错误代码如下
![2](https://user-images.githubusercontent.com/30221150/34754863-77105020-f5fb-11e7-8286-a69f86584728.png)

**Comment by huangshuwei** [comment]
麻烦配置贴下，谢谢

**Comment by 328921371** [comment]
配置是这样写的
<v-table column-width-drag :is-loading='biaoloading' is-vertical-resize is-horizontal-resize style="width:100%;margin-top: 20px;margin-bottom: 30px;" :columns="columns" :table-data="tableData" row-hover-color="#eee" row-click-color="#edf7ff" @on-custom-comp="customCompFunc" :row-height=38 title-bg-color="#eee"></v-table>

**Comment by huangshuwei** [comment]
是设置纵向自适应的问题，和这个 #79 重了。我尽快修复

**Comment by 328921371** [comment]
谢谢了,文档示例也是这样的效果,所以就来问问,辛苦了

**Comment by huangshuwei** [comment]
不客气，修复了通知你

**Comment by 328921371** [comment]
好的,谢谢

**Comment by huangshuwei** [comment]
已修复，已发布
https://github.com/huangshuwei/vue-easytable/releases/tag/1.6.5

**Comment by 328921371** [comment]
你好,我重新 npm i 更新到了1.6.5的版本,还是会出现之前的那个问题 这是我的配置,和官网的一样 <v-table column-width-drag is-horizontal-resize style="width:100%" :columns="columns" :table-data="tableData" row-hover-color="#eee" row-click-color="#edf7ff"></v-table> 
是哪里配置错了吗
又麻烦你了

**Comment by huangshuwei** [comment]
你看最新版的实例，我用了你的配置，看着没问题啊
https://jsfiddle.net/56sugjw3/1/

**Comment by huangshuwei** [comment]
最好把包卸载了，再重新安装试试。

**Comment by 328921371** [comment]
![123](https://user-images.githubusercontent.com/30221150/35137187-03bf31e8-fd23-11e7-9132-2a87b112c2a7.png)
这是你刚刚链接的截图

**Comment by 328921371** [comment]
当表格最下方没有横向滚动条的时候,拖动列宽,会出现原来的问题

**Comment by 328921371** [comment]
![123](https://user-images.githubusercontent.com/30221150/35137246-5aa86b14-fd23-11e7-905a-752d837d6353.png)

**Comment by 328921371** [comment]
![123](https://user-images.githubusercontent.com/30221150/35137335-d88f4a66-fd23-11e7-828b-e97aa46ad730.png)

**Comment by huangshuwei** [comment]
好的，重现了，重新开个issue，这是新的bug

**Comment by 328921371** [comment]
好气,图片上传不了,网速太慢了.,谢谢啦,之前就是这样子的,辛苦了辛苦了

**Comment by huangshuwei** [comment]
感谢反馈

**Comment by 328921371** [comment]
不客气,又要麻烦你了

**Comment by 328921371** [comment]
还有一个,当高度足够时,在谷歌浏览器下还是会出现纵向滚动条

**Comment by 328921371** [comment]
![111](https://user-images.githubusercontent.com/30221150/35138144-10df99f8-fd28-11e7-9cbb-96c55cd261e9.png)

**Comment by 328921371** [comment]
就是在谷歌浏览器下打开就会出现

**Comment by huangshuwei** [comment]
我这为什么没有啊，同样谷歌
https://jsfiddle.net/56sugjw3/2/

**Comment by 328921371** [comment]
还是会有的,不过没关系,这个可以通过设置 :row-height=38  来取消,,主要还是列宽拖动的问题

**Comment by huangshuwei** [comment]
如果没有列宽拖动是没问题的对吧

**Comment by 328921371** [comment]
谢谢啦,最近其他事忙了一下,忘记了这个,我还没有试,试了和你说一下效果哈,再次感谢,新年快乐

**Comment by 328921371** [comment]
我把node包删掉重新更新到1.7.0的版本,还是会有以前的问题,列宽拖动出现纵向滚动条,代码的配置和以前是一样的

**Comment by 328921371** [comment]
在吗..官方文档上面的列宽拖动好像也是这样的

**Comment by huangshuwei** [comment]
是的，列宽拖动目前还没有解决滚动条的问题

**Comment by 328921371** [comment]
谷歌浏览器打开的话,表格会出现纵向滚动条,你可以试试把你的官方文档用谷歌浏览器打开看一下,笔记本要调整到80%的大小才是正常显示,谢谢啦

**Comment by 328921371** [comment]
知道是什么原因引起的吗??我找了好久没找到

**Comment by huangshuwei** [comment]
> 谷歌浏览器打开的话,表格会出现纵向滚动条,你可以试试把你的官方文档用谷歌浏览器打开看一下,笔记本要调整到80%的大小才是正常显示,谢谢啦
我这chorme 浏览器显示正常的，你chrome 版本多少。我的是 64.0.3282.140

**Comment by 328921371** [comment]
最近忙一下没时间来这里了,我贴一下图
![biaoge](https://user-images.githubusercontent.com/30221150/37573768-538834ca-2b56-11e8-8263-7d0f7ff2257f.png)
![guge](https://user-images.githubusercontent.com/30221150/37573776-62690bf4-2b56-11e8-8e74-977a910ff781.png)

**Comment by 328921371** [comment]
不管什么比例,好像都会有横向的滚动条

**Comment by huangshuwei** [comment]
收到

**Comment by 328921371** [comment]
兼容性的问题吗,可是你那边不是正常显示的吗

**Comment by huangshuwei** [comment]
我chrome 在不放大缩小的情况下是正常的。放大缩小也会有问题

**Comment by 328921371** [comment]
笔记本的话 谷歌浏览器80%是正常的显示状态..我都有问题

**Comment by huangshuwei** [comment]
笔记本显示比例是否放大了，我这里放大的确也会有问题
![111](https://user-images.githubusercontent.com/6047141/37587799-3d57cf90-2b9b-11e8-92aa-6b0d0141ec02.png)

**Comment by 328921371** [comment]
WIN10是自动默认125%,可能是这个原因导致的

**Comment by 328921371** [comment]
在吗,问你一个问题,表格里面的内容怎么让他换行啊
