### ISSUE TITLE
能否来一份表格高度自适应？

### ISSUE THREAD

**Issue by jxharp** [Happy-Coding-Clans/vue-easytable#84]
在大屏幕2K以上分辨率的情况下，观察用户的浏览器不会最大化，经常改变浏览器大小，easytable的数据行不会随着高度改变而变化，浏览器高度增加时，会在底部留出难看的空白区域。 能否增加设置，显示数据足够2个屏幕高度的行数时，自适应高度变化？

**Comment by huangshuwei** [comment]
可以通过设置属性`is-vertical-resize`开启高度自适应配置，保证表格在一屏内显示

**Comment by jxharp** [comment]
![_ _20180115135439](https://user-images.githubusercontent.com/20125545/34928907-aeb6b9e8-f9fb-11e7-8c7d-aefe5da321c2.png)

是这样的，屏幕上的表格当数据量比较小的时候，会显得比较难看，因此我们加了空数据，让表格撑满整个屏幕。这时候is-vertical-resize属性就无效了。这个问题的潜在需求是，easytable能提供空数据或空行，撑满整个屏幕。如果能修改就万分感谢了。

**Comment by huangshuwei** [comment]
> 是这样的，屏幕上的表格当数据量比较小的时候，会显得比较难看，因此我们加了空数据，让表格撑满整个屏幕

数据不能撑满全屏时，依然全屏显示，这样感觉并不好看啊。

目前的功能是开启高度自适应配置，如果表格数据超出一屏则会在一屏内显示，如果不够一屏，则显示当前数据高度

**Comment by huangshuwei** [comment]
最早版本的纵向自适应功能，数据不够时会显示全屏。被视为bug,后来修复了😁

**Comment by jxharp** [comment]
能不能开放出来作为参数配置。有的场景，一个页面会有左右2个表格，每个表格的数据量不一致，配合背景色，显得很难看。 求大神吧纵向自适应开放出来作为配置吧。

**Comment by jxharp** [comment]
纵向自适应这个真不是bug，很多场景下用到。尤其是一些后台管理系统，一页多个表格的时候。希望能加上啊。

**Comment by huangshuwei** [comment]
稍等，有点事，一会回复你

**Comment by huangshuwei** [comment]
纵向自适应，当数据不够一屏时，你是要这种效果吗：
![default](https://user-images.githubusercontent.com/6047141/34971769-c3ed84ec-fab7-11e7-8bef-844d6bcbb0cb.png)

**Comment by jxharp** [comment]
是这样的，如图， 就是希望如图表格撑满屏幕，不论是否有数据。 这样就不会出现下面空着一大块。想象一下，一个页面有多个表格，每个表格数据量不一致，又有背景色，这样就不好玩了。目前我们自己写的，当改变浏览器高度就不会自适应了，如果每个都写js单独处理，那实在很累。easytable原生能支持就好了。
![tim 20180116171215](https://user-images.githubusercontent.com/20125545/34980767-7583a600-fae0-11e7-8ca6-3a0ddbf63422.png)

**Comment by jxharp** [comment]
这个截图的意思，就是表格线都有，撑满屏幕，但是数据只有一部分。

**Comment by huangshuwei** [comment]
明白你的意思，这种需求真的不好支持啊😭

**Comment by zxrliuyan** [comment]
自己可以根据行数计算 row*40来设置Height，我就是这么干的

**Comment by jxharp** [comment]
我们也是这样干的，但是改变分辨率或改变浏览器窗口大小，就不会自适应了。如果用js控制，又太影响性能了。

**Comment by yangdan8** [comment]
自适应高度与固定表头不能一起使用
