### ISSUE TITLE
當自適應的table放在dialog中會跑板

### ISSUE THREAD

**Issue by mixwade32517** [Happy-Coding-Clans/vue-easytable#89]
正常的樣子
<img width="614" alt="2018-01-18 6 03 21" src="https://user-images.githubusercontent.com/8232987/35092314-f603e746-fc79-11e7-88dc-213e0aab5829.png">

放在dialog中的樣子

<img width="1158" alt="2018-01-18 5 54 50" src="https://user-images.githubusercontent.com/8232987/35092335-041e6af4-fc7a-11e7-923c-928c46756793.png">

**Comment by huangshuwei** [comment]
参考这个 issue
https://github.com/huangshuwei/vue-easytable/issues/45

**Comment by huangshuwei** [comment]
Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
